package controllers

import (
	"bytes"
	"encoding/json"
	"mycorrhizal/models"
	"net/http"
	"net/http/httptest"
	"strconv"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

// T6 controller tests for
// the FieldDefinition/FieldValue API surface. These use the package's
// setupRouter() AutoMigrate idiom (see field_definition_real_db_test.go for
// the real-migrated-schema round trip).

func createTestDefinition(t *testing.T, db *gorm.DB, userID uint, key string) models.FieldDefinition {
	t.Helper()
	return models.FieldDefinition{
		UserID:      userID,
		Label:       "Test " + key,
		Key:         key,
		Target:      models.FieldDefinitionTargetContact,
		Type:        models.FieldTypeString,
		Projection:  "internal-only",
		Sensitivity: models.RelationshipSensitivityNormal,
	}
}

func TestCreateFieldDefinition(t *testing.T) {
	db, router := setupRouter()
	router.POST("/field-definitions", withValidated(func() any { return &models.FieldDefinitionInput{} }), CreateFieldDefinition)

	var user models.User
	db.First(&user)

	payload := models.FieldDefinitionInput{
		Label:      "Gender identity",
		Key:        "gender_identity",
		Target:     models.FieldDefinitionTargetContact,
		Type:       models.FieldTypeString,
		Projection: "internal-only",
	}
	jsonValue, _ := json.Marshal(payload)
	req, _ := http.NewRequest("POST", "/field-definitions", bytes.NewBuffer(jsonValue))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusCreated, w.Code)

	var count int64
	db.Model(&models.FieldDefinition{}).Count(&count)
	assert.EqualValues(t, 1, count)

	var saved models.FieldDefinition
	require.NoError(t, db.First(&saved).Error)
	assert.Equal(t, user.ID, saved.UserID)
	assert.Equal(t, "internal-only", saved.Projection, "default projection applied when omitted")
	assert.Equal(t, "normal", saved.Sensitivity, "default sensitivity applied when omitted")
	assert.NotEmpty(t, saved.ID, "UUID generated by BeforeCreate")
}

func TestCreateFieldDefinitionRejectsDuplicateKey(t *testing.T) {
	db, router := setupRouter()
	router.POST("/field-definitions", withValidated(func() any { return &models.FieldDefinitionInput{} }), CreateFieldDefinition)

	var user models.User
	db.First(&user)
	def := createTestDefinition(t, db, user.ID, "dup_key")
	require.NoError(t, db.Create(&def).Error)

	payload := models.FieldDefinitionInput{Label: "Duplicate", Key: "dup_key", Type: models.FieldTypeString}
	jsonValue, _ := json.Marshal(payload)
	req, _ := http.NewRequest("POST", "/field-definitions", bytes.NewBuffer(jsonValue))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusConflict, w.Code)
}

func TestGetFieldDefinition(t *testing.T) {
	db, router := setupRouter()
	router.GET("/field-definitions/:id", GetFieldDefinition)

	var user models.User
	db.First(&user)
	def := createTestDefinition(t, db, user.ID, "nickname")
	require.NoError(t, db.Create(&def).Error)

	req, _ := http.NewRequest("GET", "/field-definitions/"+def.ID, nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	var body models.FieldDefinition
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &body))
	assert.Equal(t, def.ID, body.ID)
	assert.Equal(t, "nickname", body.Key)
}

func TestGetFieldDefinitionNotFoundForUnknownID(t *testing.T) {
	_, router := setupRouter()
	router.GET("/field-definitions/:id", GetFieldDefinition)

	req, _ := http.NewRequest("GET", "/field-definitions/does-not-exist", nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusNotFound, w.Code)
}

func TestListFieldDefinitions(t *testing.T) {
	db, router := setupRouter()
	router.GET("/field-definitions", ListFieldDefinitions)

	var user models.User
	db.First(&user)
	zeta := createTestDefinition(t, db, user.ID, "zeta")
	alpha := createTestDefinition(t, db, user.ID, "alpha")
	require.NoError(t, db.Create(&zeta).Error)
	require.NoError(t, db.Create(&alpha).Error)

	req, _ := http.NewRequest("GET", "/field-definitions", nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	var body struct {
		FieldDefinitions []models.FieldDefinition `json:"field_definitions"`
		Total            int64                    `json:"total"`
	}
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &body))
	assert.Len(t, body.FieldDefinitions, 2)
	assert.Equal(t, int64(2), body.Total)
}

func TestUpdateFieldDefinition(t *testing.T) {
	db, router := setupRouter()
	router.PUT("/field-definitions/:id", withValidated(func() any { return &models.FieldDefinitionInput{} }), UpdateFieldDefinition)

	var user models.User
	db.First(&user)
	def := createTestDefinition(t, db, user.ID, "nickname")
	require.NoError(t, db.Create(&def).Error)

	// Upgrade the definition in place: label + type change, key stays stable.
	payload := models.FieldDefinitionInput{
		Label:       "Preferred name",
		Key:         "different_key", // must be ignored on update
		Type:        models.FieldTypeEnum,
		Constraints: models.FieldConstraints{Values: []string{"Alex", "Sam"}},
	}
	jsonValue, _ := json.Marshal(payload)
	req, _ := http.NewRequest("PUT", "/field-definitions/"+def.ID, bytes.NewBuffer(jsonValue))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusOK, w.Code)

	var reloaded models.FieldDefinition
	require.NoError(t, db.First(&reloaded, "id = ?", def.ID).Error)
	assert.Equal(t, "Preferred name", reloaded.Label)
	assert.Equal(t, models.FieldTypeEnum, reloaded.Type)
	assert.Equal(t, []string{"Alex", "Sam"}, reloaded.Constraints.Values)
	assert.Equal(t, "nickname", reloaded.Key, "Key is immutable on update")
}

func TestDeleteFieldDefinition(t *testing.T) {
	db, router := setupRouter()
	router.DELETE("/field-definitions/:id", DeleteFieldDefinition)

	var user models.User
	db.First(&user)
	def := createTestDefinition(t, db, user.ID, "nickname")
	require.NoError(t, db.Create(&def).Error)

	req, _ := http.NewRequest("DELETE", "/field-definitions/"+def.ID, nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusOK, w.Code)

	var defCount int64
	db.Model(&models.FieldDefinition{}).Count(&defCount)
	assert.Zero(t, defCount)

	// The FieldValue cascade is enforced by the hand-written migration's ON
	// DELETE CASCADE FK, which AutoMigrate (what this test's setupRouter
	// builds) does not replicate -- so it is asserted against the real
	// migrated schema in field_definition_real_db_test.go instead.
}

// --- Ownership scoping ---

func TestFieldDefinitionOwnershipScoping(t *testing.T) {
	db, router := setupRouter()
	router.GET("/field-definitions", ListFieldDefinitions)
	router.GET("/field-definitions/:id", GetFieldDefinition)
	router.PUT("/field-definitions/:id", withValidated(func() any { return &models.FieldDefinitionInput{} }), UpdateFieldDefinition)
	router.DELETE("/field-definitions/:id", DeleteFieldDefinition)

	var user models.User
	db.First(&user)
	otherUser := models.User{Username: "other", Password: "password123", Email: "other@example.com"}
	require.NoError(t, db.Create(&otherUser).Error)

	otherDef := createTestDefinition(t, db, otherUser.ID, "not_yours")
	require.NoError(t, db.Create(&otherDef).Error)

	// List must not include the other user's definition.
	listReq, _ := http.NewRequest("GET", "/field-definitions", nil)
	listW := httptest.NewRecorder()
	router.ServeHTTP(listW, listReq)
	var listBody struct {
		FieldDefinitions []models.FieldDefinition `json:"field_definitions"`
	}
	require.NoError(t, json.Unmarshal(listW.Body.Bytes(), &listBody))
	assert.Len(t, listBody.FieldDefinitions, 0)

	// Get/update/delete of a cross-user definition are all 404.
	for _, m := range []struct {
		method string
		body   any
	}{
		{"GET", nil},
		{"PUT", models.FieldDefinitionInput{Label: "x", Key: "y", Type: models.FieldTypeString}},
		{"DELETE", nil},
	} {
		var buf bytes.Buffer
		if m.body != nil {
			b, _ := json.Marshal(m.body)
			buf.Write(b)
		}
		req, _ := http.NewRequest(m.method, "/field-definitions/"+otherDef.ID, &buf)
		req.Header.Set("Content-Type", "application/json")
		w := httptest.NewRecorder()
		router.ServeHTTP(w, req)
		assert.Equal(t, http.StatusNotFound, w.Code, "%s on cross-user definition must be 404", m.method)
	}
}

// --- FieldValue endpoints ---

// setupFieldValueRoutes wires the nested field-value routes onto a fresh
// router with one user, one contact, and a default string definition.
func setupFieldValueRoutes(t *testing.T) (*gorm.DB, *gin.Engine, models.User, models.Contact, models.FieldDefinition) {
	t.Helper()
	db, router := setupRouter()
	router.GET("/contacts/:id/field-values", ListContactFieldValues)
	router.PUT("/contacts/:id/field-values", withValidated(func() any { return &models.ContactFieldValuesInput{} }), ReplaceContactFieldValues)

	var user models.User
	db.First(&user)
	contact := models.Contact{UserID: user.ID, Firstname: "Alice"}
	require.NoError(t, db.Create(&contact).Error)
	def := createTestDefinition(t, db, user.ID, "nickname")
	require.NoError(t, db.Create(&def).Error)
	return db, router, user, contact, def
}

func TestReplaceContactFieldValues_RoundTrip(t *testing.T) {
	db, router, user, contact, def := setupFieldValueRoutes(t)

	payload := models.ContactFieldValuesInput{
		FieldValues: []models.FieldValueInput{
			{FieldDefinitionID: def.ID, Value: json.RawMessage(`"Al"`)},
		},
	}
	jsonValue, _ := json.Marshal(payload)
	req, _ := http.NewRequest("PUT", "/contacts/"+strconv.Itoa(int(contact.ID))+"/field-values", bytes.NewBuffer(jsonValue))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusOK, w.Code)

	var saved []models.FieldValue
	require.NoError(t, db.Where("entity_id = ? AND user_id = ?", contact.VCardUID, user.ID).Find(&saved).Error)
	require.Len(t, saved, 1)
	assert.Equal(t, def.ID, saved[0].FieldDefinitionID)
	assert.Equal(t, `"Al"`, string(saved[0].Value))

	// Read back through the GET endpoint.
	getReq, _ := http.NewRequest("GET", "/contacts/"+strconv.Itoa(int(contact.ID))+"/field-values", nil)
	getW := httptest.NewRecorder()
	router.ServeHTTP(getW, getReq)
	assert.Equal(t, http.StatusOK, getW.Code)
	var listBody struct {
		FieldValues []models.FieldValue `json:"field_values"`
	}
	require.NoError(t, json.Unmarshal(getW.Body.Bytes(), &listBody))
	require.Len(t, listBody.FieldValues, 1)
	assert.Equal(t, `"Al"`, string(listBody.FieldValues[0].Value))
}

func TestReplaceContactFieldValues_TypeMismatchIs400(t *testing.T) {
	_, router, _, contact, def := setupFieldValueRoutes(t)

	// def is a string field; a JSON number must be rejected as a 400.
	payload := models.ContactFieldValuesInput{
		FieldValues: []models.FieldValueInput{
			{FieldDefinitionID: def.ID, Value: json.RawMessage(`42`)},
		},
	}
	jsonValue, _ := json.Marshal(payload)
	req, _ := http.NewRequest("PUT", "/contacts/"+strconv.Itoa(int(contact.ID))+"/field-values", bytes.NewBuffer(jsonValue))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusBadRequest, w.Code)
}

func TestReplaceContactFieldValues_RejectsNotOwnedDefinition(t *testing.T) {
	db, router, _, contact, _ := setupFieldValueRoutes(t)

	var user models.User
	db.First(&user)
	otherUser := models.User{Username: "other", Password: "password123", Email: "other@example.com"}
	require.NoError(t, db.Create(&otherUser).Error)
	otherDef := createTestDefinition(t, db, otherUser.ID, "not_yours")
	require.NoError(t, db.Create(&otherDef).Error)

	payload := models.ContactFieldValuesInput{
		FieldValues: []models.FieldValueInput{
			{FieldDefinitionID: otherDef.ID, Value: json.RawMessage(`"x"`)},
		},
	}
	jsonValue, _ := json.Marshal(payload)
	req, _ := http.NewRequest("PUT", "/contacts/"+strconv.Itoa(int(contact.ID))+"/field-values", bytes.NewBuffer(jsonValue))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusBadRequest, w.Code, "a value for someone else's definition is rejected, not silently accepted")
}

func TestReplaceContactFieldValues_MultiListCase(t *testing.T) {
	db, router, user, contact, _ := setupFieldValueRoutes(t)

	// A Multi enum definition: value must be a JSON array.
	def := models.FieldDefinition{
		UserID:      user.ID,
		Label:       "Pronouns",
		Key:         "pronouns",
		Target:      models.FieldDefinitionTargetContact,
		Type:        models.FieldTypeEnum,
		Constraints: models.FieldConstraints{Values: []string{"she/her", "he/him", "they/them"}, Multi: true},
		Projection:  "internal-only",
		Sensitivity: models.RelationshipSensitivityNormal,
	}
	require.NoError(t, db.Create(&def).Error)

	payload := models.ContactFieldValuesInput{
		FieldValues: []models.FieldValueInput{
			{FieldDefinitionID: def.ID, Value: json.RawMessage(`["she/her","they/them"]`)},
		},
	}
	jsonValue, _ := json.Marshal(payload)
	req, _ := http.NewRequest("PUT", "/contacts/"+strconv.Itoa(int(contact.ID))+"/field-values", bytes.NewBuffer(jsonValue))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)
	assert.Equal(t, http.StatusOK, w.Code)

	// A scalar string is NOT a valid list value.
	bad := models.ContactFieldValuesInput{
		FieldValues: []models.FieldValueInput{
			{FieldDefinitionID: def.ID, Value: json.RawMessage(`"she/her"`)},
		},
	}
	badJSON, _ := json.Marshal(bad)
	badReq, _ := http.NewRequest("PUT", "/contacts/"+strconv.Itoa(int(contact.ID))+"/field-values", bytes.NewBuffer(badJSON))
	badReq.Header.Set("Content-Type", "application/json")
	badW := httptest.NewRecorder()
	router.ServeHTTP(badW, badReq)
	assert.Equal(t, http.StatusBadRequest, badW.Code, "a scalar for a Multi field is rejected")

	// One invalid element fails the whole list.
	partial := models.ContactFieldValuesInput{
		FieldValues: []models.FieldValueInput{
			{FieldDefinitionID: def.ID, Value: json.RawMessage(`["she/her","xyz"]`)},
		},
	}
	partialJSON, _ := json.Marshal(partial)
	partialReq, _ := http.NewRequest("PUT", "/contacts/"+strconv.Itoa(int(contact.ID))+"/field-values", bytes.NewBuffer(partialJSON))
	partialReq.Header.Set("Content-Type", "application/json")
	partialW := httptest.NewRecorder()
	router.ServeHTTP(partialW, partialReq)
	assert.Equal(t, http.StatusBadRequest, partialW.Code, "one invalid element fails the whole list")
}

func TestReplaceContactFieldValues_FullReplaceDeletesAbsent(t *testing.T) {
	db, router, user, contact, _ := setupFieldValueRoutes(t)

	keep := createTestDefinition(t, db, user.ID, "keep_me")
	drop := createTestDefinition(t, db, user.ID, "drop_me")
	require.NoError(t, db.Create(&keep).Error)
	require.NoError(t, db.Create(&drop).Error)
	for _, def := range []models.FieldDefinition{keep, drop} {
		require.NoError(t, db.Create(&models.FieldValue{
			FieldDefinitionID: def.ID,
			UserID:            user.ID,
			EntityID:          contact.VCardUID,
			Value:             json.RawMessage(`"v"`),
		}).Error)
	}

	// Replace with only keep_me present: drop_me's value must be deleted.
	payload := models.ContactFieldValuesInput{
		FieldValues: []models.FieldValueInput{
			{FieldDefinitionID: keep.ID, Value: json.RawMessage(`"new"`)},
		},
	}
	jsonValue, _ := json.Marshal(payload)
	req, _ := http.NewRequest("PUT", "/contacts/"+strconv.Itoa(int(contact.ID))+"/field-values", bytes.NewBuffer(jsonValue))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)
	assert.Equal(t, http.StatusOK, w.Code)

	var saved []models.FieldValue
	require.NoError(t, db.Where("entity_id = ? AND user_id = ?", contact.VCardUID, user.ID).Find(&saved).Error)
	require.Len(t, saved, 1)
	assert.Equal(t, keep.ID, saved[0].FieldDefinitionID)
	assert.Equal(t, `"new"`, string(saved[0].Value), "existing row updated in place, not duplicated")
}

func TestListContactFieldValues_ContactNotFound(t *testing.T) {
	_, router := setupRouter()
	router.GET("/contacts/:id/field-values", ListContactFieldValues)

	req, _ := http.NewRequest("GET", "/contacts/999999/field-values", nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusNotFound, w.Code)
}

func TestReplaceContactFieldValues_EmptyPayloadClearsAll(t *testing.T) {
	db, router, user, contact, _ := setupFieldValueRoutes(t)

	// Pre-seed two values.
	def1 := createTestDefinition(t, db, user.ID, "field_a")
	def2 := createTestDefinition(t, db, user.ID, "field_b")
	require.NoError(t, db.Create(&def1).Error)
	require.NoError(t, db.Create(&def2).Error)
	for _, def := range []models.FieldDefinition{def1, def2} {
		require.NoError(t, db.Create(&models.FieldValue{
			FieldDefinitionID: def.ID,
			UserID:            user.ID,
			EntityID:          contact.VCardUID,
			Value:             json.RawMessage(`"x"`),
		}).Error)
	}

	// Send an empty payload: both values must be deleted.
	payload := models.ContactFieldValuesInput{FieldValues: []models.FieldValueInput{}}
	jsonValue, _ := json.Marshal(payload)
	req, _ := http.NewRequest("PUT", "/contacts/"+strconv.Itoa(int(contact.ID))+"/field-values", bytes.NewBuffer(jsonValue))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusOK, w.Code)

	var saved []models.FieldValue
	require.NoError(t, db.Where("entity_id = ? AND user_id = ?", contact.VCardUID, user.ID).Find(&saved).Error)
	assert.Len(t, saved, 0, "empty payload must delete every existing value")
}

func TestReplaceContactFieldValues_ContactNotFound(t *testing.T) {
	_, router, _, _, def := setupFieldValueRoutes(t)

	payload := models.ContactFieldValuesInput{
		FieldValues: []models.FieldValueInput{
			{FieldDefinitionID: def.ID, Value: json.RawMessage(`"v"`)},
		},
	}
	jsonValue, _ := json.Marshal(payload)
	req, _ := http.NewRequest("PUT", "/contacts/999999/field-values", bytes.NewBuffer(jsonValue))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusNotFound, w.Code)
}
