// Package releasenotes is the code side of REL-05, the changelog policy
// (issue #449, docs/changelog-policy.md).
//
// The changelog is the GitHub Release notes. The "what changed" list is
// generated by GitHub from labelled PRs (.github/release.yml). The
// operator-facing part — "Upgrade notes", "Security-relevant changes" and
// "Breaking changes" — is hand-written in each PR's description and harvested
// here at release time: given the PRs merged in a release's range, Assemble
// pulls their `## Upgrade notes` / `## Security-relevant changes` / `##
// Breaking changes` sections and stitches them into one block for the release
// body.
//
// Assemble is a pure transformation so it is fully unit-tested; the workflow
// (docker-publish.yml, create-release) does the `gh pr list --json` call and
// feeds the JSON to cmd/releasenotes on stdin.
package releasenotes

import (
	"fmt"
	"regexp"
	"strings"
)

// PR is one merged pull request in a release's range. The field tags match
// `gh pr list --json number,title,url,body`.
type PR struct {
	Number int    `json:"number"`
	Title  string `json:"title"`
	URL    string `json:"url"`
	Body   string `json:"body"`
}

// Section titles harvested from PR bodies, and the release-body headings they
// are collected under. Matching is case-insensitive; a PR may use any heading
// level 2–4.
const (
	upgradeNotesTitle            = "upgrade notes"
	securityRelevantChangesTitle = "security-relevant changes"
	breakingChangesTitle         = "breaking changes"

	// UpgradeNotesHeading / SecurityRelevantChangesHeading /
	// BreakingChangesHeading are the level-2 headings the assembled block uses
	// in the release body.
	UpgradeNotesHeading            = "## Upgrade notes"
	SecurityRelevantChangesHeading = "## Security-relevant changes"
	BreakingChangesHeading         = "## Breaking changes"

	// NoUpgradeActionRequired is the standing text when no PR in the range
	// carried an upgrade note. It still ships, so every release answers the
	// "does this upgrade need anything of me?" question explicitly.
	NoUpgradeActionRequired = "None — no action required for an instance already on ≥ v0.6.0."
)

// headingRe matches a Markdown ATX heading, capturing the hashes and the text.
var headingRe = regexp.MustCompile(`^(#{1,6})[ \t]+(.*?)[ \t]*#*[ \t]*$`)

// Assemble returns the Markdown block for the release body: an "Upgrade notes"
// section always; a "Security-relevant changes" section only if at least one PR
// carried one; and a "Breaking changes" section only if at least one PR carried
// one. The security section sits immediately after the upgrade notes so an
// operator scanning the release body cannot miss a security-relevant action
// among feature notes (issue #953). PRs are processed in the given order.
func Assemble(prs []PR) string {
	var upgrades, security, breakings []string
	for _, pr := range prs {
		if s := extractSection(pr.Body, upgradeNotesTitle); s != "" {
			upgrades = append(upgrades, attribute(pr, s))
		}
		if s := extractSection(pr.Body, securityRelevantChangesTitle); s != "" {
			security = append(security, attribute(pr, s))
		}
		if s := extractSection(pr.Body, breakingChangesTitle); s != "" {
			breakings = append(breakings, attribute(pr, s))
		}
	}

	var b strings.Builder
	b.WriteString(UpgradeNotesHeading)
	b.WriteString("\n\n")
	if len(upgrades) == 0 {
		b.WriteString(NoUpgradeActionRequired)
		b.WriteString("\n")
	} else {
		b.WriteString(strings.Join(upgrades, "\n\n"))
		b.WriteString("\n")
	}

	writeOptionalSection(&b, SecurityRelevantChangesHeading, security)
	writeOptionalSection(&b, BreakingChangesHeading, breakings)

	return b.String()
}

// writeOptionalSection appends a "\n<section>\n\n<attributed blocks>\n" block
// when blocks is non-empty and writes nothing otherwise. The security and
// breaking sections are both conditional, so they share this.
func writeOptionalSection(b *strings.Builder, heading string, blocks []string) {
	if len(blocks) == 0 {
		return
	}
	b.WriteString("\n")
	b.WriteString(heading)
	b.WriteString("\n\n")
	b.WriteString(strings.Join(blocks, "\n\n"))
	b.WriteString("\n")
}

// attribute prefixes a harvested block with a link to the PR it came from.
func attribute(pr PR, body string) string {
	ref := fmt.Sprintf("#%d", pr.Number)
	if pr.URL != "" {
		ref = fmt.Sprintf("[#%d](%s)", pr.Number, pr.URL)
	}
	return fmt.Sprintf("**%s** — %s", ref, body)
}

// extractSection returns the trimmed body of the first heading in md whose text
// equals title (case-insensitive), up to the next heading at the same or a
// higher level (fewer or equal `#`), or the end of the document. It returns ""
// when no such heading exists.
func extractSection(md, title string) string {
	lines := strings.Split(md, "\n")
	start, level := -1, 0
	for i, line := range lines {
		m := headingRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		if strings.EqualFold(strings.TrimSpace(m[2]), title) {
			start = i + 1
			level = len(m[1])
			break
		}
	}
	if start == -1 {
		return ""
	}

	end := len(lines)
	for i := start; i < len(lines); i++ {
		m := headingRe.FindStringSubmatch(lines[i])
		if m != nil && len(m[1]) <= level {
			end = i
			break
		}
	}
	return strings.TrimSpace(strings.Join(lines[start:end], "\n"))
}
