import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright configuration for the service-worker upgrade suite (issue #476,
 * WEB-02).
 *
 * This is deliberately a SEPARATE config from playwright.config.ts:
 *
 * - The main suite runs against the all-in-one docker stack (nginx + backend)
 *   on port 7300, which serves a single fixed build. Service-worker upgrades
 *   need an origin that can swap between two builds mid-test, so this suite
 *   starts its own harness server (frontend/e2e/sw-upgrade/sw-server.mjs)
 *   that stages "build a" and "build b" and lets each test flip the active
 *   one. The harness is a plain static server -- no backend is required,
 *   because these tests assert on the app shell, the service worker lifecycle
 *   and CacheStorage, none of which needs the API.
 * - `frontend-dev` cannot serve a real /service-worker.js (CLAUDE.md, T51), so
 *   this suite only ever runs against real production builds -- the fixtures
 *   the harness serves are generated by `vite build`, and `yarn build` output
 *   is required for the main-suite SW specs too.
 * - The main suite's e2e/global-setup.ts hardcodes http://localhost:7300, and
 *   so does this config -- the harness takes over the same port the docker
 *   stack would use, which is why the two suites must never run at the same
 *   time (the CI job for this suite does not start the docker stack).
 *
 * Run:  cd frontend && npx playwright test -c playwright.sw.config.ts
 */
const port = Number(process.env.SW_TEST_PORT || 7300);
const baseURL = `http://localhost:${port}`;

export default defineConfig({
  testDir: './e2e/sw-upgrade',

  // The harness's active build is shared server state -- each test flips it at
  // its own pace, so tests must never overlap. A single worker also serialises
  // the two browser projects.
  fullyParallel: false,
  workers: 1,

  forbidOnly: !!process.env.CI,
  // Issue #974: same nightly non-retried leg as playwright.config.ts — 0
  // retries on the `schedule` run so a flake here gets a hard-fail surface
  // at least once a day instead of staying green behind the retry forever.
  retries: process.env.CI ? (process.env.GITHUB_EVENT_NAME === 'schedule' ? 0 : 1) : 0,

  reporter: [['html', { open: 'never', outputFolder: 'playwright-report-sw' }], ['list']],

  outputDir: 'test-results-sw',

  webServer: {
    command: 'node e2e/sw-upgrade/webServer.mjs',
    url: `${baseURL}/__swtest/status`,
    reuseExistingServer: !process.env.CI,
    // First run in a clean checkout also builds both fixtures from source.
    timeout: 600_000,
    env: {
      ...process.env,
      SW_TEST_FIXTURE_REBUILD: process.env.CI ? '1' : '0',
    },
  },

  use: {
    baseURL,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'on-first-retry',
    serviceWorkers: 'allow',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
  ],

  timeout: 90_000,
  expect: {
    timeout: 10_000,
  },
});
