// Package tsapi generates TypeScript types for backend/openapi.yaml's
// components.schemas, into frontend/src/generated/openapi.ts.
//
// The backend is validated against the spec (TestOpenAPIRouteCoverage,
// TestOpenAPIResponseSpotCheck, Schemathesis), so the spec is the trustworthy
// middle of the frontend↔backend contract. The web client's API types are
// hand-written (frontend/src/api/*.ts); this generator emits the spec's view
// of the same shapes so frontend/src/api/contractConformance.ts can assert,
// at `tsc --noEmit` time, that the two agree — closing CLAUDE.md frontend
// traps #4 (hand-mirrored enum lists) and #8 (a Go `omitempty` field typed as
// required in TS) for every entity the conformance file covers.
//
// Mapping (OpenAPI 3.0 → TS):
//   - $ref                        → the referenced schema's name
//   - required property           → `name: T`; otherwise `name?: T`
//   - nullable: true              → `T | null`
//   - enum                        → a literal union (`'a' | 'b'`)
//   - string/integer/number/bool  → string/number/number/boolean
//   - array                       → `T[]`
//   - object with properties      → an inline object type
//   - object with only additionalProperties → `Record<string, T>`
//     (`additionalProperties: true` → `Record<string, unknown>`)
//   - allOf                       → an intersection; oneOf/anyOf → a union
//   - no type and no composition  → `unknown`
//
// An object that declares properties AND `additionalProperties` is emitted
// with its declared properties only: the extra keys are opaque by contract,
// and an index signature would make `keyof` the whole string space (which
// defeats the key-set half of the conformance check).
//
// Output is deterministic: schemas and properties are emitted in sorted
// order, so the drift test (backend/tsapi_types_test.go) compares stable
// bytes.
package tsapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// OutputPath is the generated file, repo-relative.
const OutputPath = "frontend/src/generated/openapi.ts"

// Header is the fixed preamble of the generated file.
const Header = `// Code generated by ` + "`cd backend && go run ./cmd/gentsapi`" + ` (or ` + "`make gen-ts-api`" + `). DO NOT EDIT.
//
// TypeScript mirror of backend/openapi.yaml components.schemas. The spec is
// the source of truth: edit it, then regenerate. The drift test
// backend/tsapi_types_test.go (TestGeneratedTSTypesMatchSpec) fails until this
// file is regenerated. frontend/src/api/contractConformance.ts asserts the
// hand-written API types agree with these at ` + "`tsc --noEmit`" + ` time.
//
// Types only — nothing here emits runtime code.

`

var identRe = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// Generate renders every components.schemas entry of doc as an exported TS
// type alias.
func Generate(doc *openapi3.T) ([]byte, error) {
	if doc.Components == nil || len(doc.Components.Schemas) == 0 {
		return nil, fmt.Errorf("spec has no components.schemas")
	}
	names := make([]string, 0, len(doc.Components.Schemas))
	for name := range doc.Components.Schemas {
		if !identRe.MatchString(name) {
			return nil, fmt.Errorf("schema name %q is not a valid TypeScript identifier", name)
		}
		names = append(names, name)
	}
	sort.Strings(names)

	var buf bytes.Buffer
	buf.WriteString(Header)
	for i, name := range names {
		ref := doc.Components.Schemas[name]
		if ref == nil || ref.Value == nil {
			return nil, fmt.Errorf("schema %s is unresolved", name)
		}
		// Render the schema's own body, not a self-reference.
		body, err := renderSchema(ref.Value, 0)
		if err != nil {
			return nil, fmt.Errorf("schema %s: %w", name, err)
		}
		if i > 0 {
			buf.WriteString("\n")
		}
		fmt.Fprintf(&buf, "export type %s = %s;\n", name, body)
	}
	return buf.Bytes(), nil
}

// renderRef renders a schema reference: the component name for a $ref,
// otherwise the inline schema body.
func renderRef(ref *openapi3.SchemaRef, depth int) (string, error) {
	if ref == nil {
		return "unknown", nil
	}
	if ref.Ref != "" {
		const prefix = "#/components/schemas/"
		if !strings.HasPrefix(ref.Ref, prefix) {
			return "", fmt.Errorf("unsupported $ref %q (only %s* is supported)", ref.Ref, prefix)
		}
		return strings.TrimPrefix(ref.Ref, prefix), nil
	}
	if ref.Value == nil {
		return "", fmt.Errorf("unresolved inline schema")
	}
	return renderSchema(ref.Value, depth)
}

func renderSchema(s *openapi3.Schema, depth int) (string, error) {
	t, err := renderNonNull(s, depth)
	if err != nil {
		return "", err
	}
	if s.Nullable && t != "unknown" {
		if hasTopLevelOperator(t, '&') {
			t = "(" + t + ")"
		}
		return t + " | null", nil
	}
	return t, nil
}

func renderNonNull(s *openapi3.Schema, depth int) (string, error) {
	switch {
	case len(s.AllOf) > 0:
		return joinRefs(s.AllOf, " & ", depth)
	case len(s.OneOf) > 0:
		return joinRefs(s.OneOf, " | ", depth)
	case len(s.AnyOf) > 0:
		return joinRefs(s.AnyOf, " | ", depth)
	}
	if len(s.Enum) > 0 {
		parts := make([]string, 0, len(s.Enum))
		for _, v := range s.Enum {
			if v == nil {
				continue // nullable enums carry null via Nullable
			}
			lit, err := literal(v)
			if err != nil {
				return "", err
			}
			parts = append(parts, lit)
		}
		return strings.Join(parts, " | "), nil
	}
	var typ string
	if s.Type != nil && len(*s.Type) > 0 {
		if len(*s.Type) > 1 {
			return "", fmt.Errorf("multi-valued type %v is not supported (OpenAPI 3.0)", *s.Type)
		}
		typ = (*s.Type)[0]
	}
	switch typ {
	case "string":
		return "string", nil
	case "integer", "number":
		return "number", nil
	case "boolean":
		return "boolean", nil
	case "array":
		item, err := renderRef(s.Items, depth)
		if err != nil {
			return "", err
		}
		if needsParens(item) {
			return "(" + item + ")[]", nil
		}
		return item + "[]", nil
	case "object", "":
		if len(s.Properties) > 0 {
			return renderObject(s, depth)
		}
		if ap := s.AdditionalProperties.Schema; ap != nil {
			inner, err := renderRef(ap, depth)
			if err != nil {
				return "", err
			}
			return "Record<string, " + inner + ">", nil
		}
		if typ == "object" {
			return "Record<string, unknown>", nil
		}
		return "unknown", nil
	}
	return "", fmt.Errorf("unsupported schema type %q", typ)
}

func joinRefs(refs openapi3.SchemaRefs, sep string, depth int) (string, error) {
	parts := make([]string, 0, len(refs))
	for _, r := range refs {
		p, err := renderRef(r, depth)
		if err != nil {
			return "", err
		}
		if needsParens(p) {
			p = "(" + p + ")"
		}
		parts = append(parts, p)
	}
	return strings.Join(parts, sep), nil
}

func renderObject(s *openapi3.Schema, depth int) (string, error) {
	required := make(map[string]bool, len(s.Required))
	for _, r := range s.Required {
		required[r] = true
	}
	keys := make([]string, 0, len(s.Properties))
	for k := range s.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, r := range s.Required {
		if _, ok := s.Properties[r]; !ok {
			return "", fmt.Errorf("required property %q is not declared in properties", r)
		}
	}

	indent := strings.Repeat("  ", depth+1)
	var b strings.Builder
	b.WriteString("{\n")
	for _, k := range keys {
		t, err := renderRef(s.Properties[k], depth+1)
		if err != nil {
			return "", fmt.Errorf("property %s: %w", k, err)
		}
		name := k
		if !identRe.MatchString(k) {
			name = quote(k)
		}
		opt := "?"
		if required[k] {
			opt = ""
		}
		fmt.Fprintf(&b, "%s%s%s: %s;\n", indent, name, opt, t)
	}
	b.WriteString(strings.Repeat("  ", depth))
	b.WriteString("}")
	return b.String(), nil
}

// needsParens reports whether t is a union or intersection at its top level
// and so must be parenthesized before being combined with another operator
// or an array suffix.
func needsParens(t string) bool {
	return hasTopLevelOperator(t, '|') || hasTopLevelOperator(t, '&')
}

// hasTopLevelOperator reports whether op appears in t outside any
// braces/brackets/parens/angle brackets or string literal.
func hasTopLevelOperator(t string, op byte) bool {
	depth := 0
	inStr := false
	for i := 0; i < len(t); i++ {
		c := t[i]
		switch {
		case inStr:
			switch c {
			case '\\':
				i++
			case '\'':
				inStr = false
			}
		case c == '\'':
			inStr = true
		case c == '{' || c == '(' || c == '[' || c == '<':
			depth++
		case c == '}' || c == ')' || c == ']' || c == '>':
			depth--
		case c == op && depth == 0:
			return true
		}
	}
	return false
}

func literal(v any) (string, error) {
	switch x := v.(type) {
	case string:
		return quote(x), nil
	case bool, float64, int, int64:
		return fmt.Sprint(x), nil
	}
	return "", fmt.Errorf("unsupported enum value %#v", v)
}

// quote renders a single-quoted TS string literal.
func quote(s string) string {
	// json.Marshal gives a correctly-escaped double-quoted string; swap the
	// delimiters to match the frontend's single-quote style.
	j, _ := json.Marshal(s)
	inner := string(j[1 : len(j)-1])
	inner = strings.ReplaceAll(inner, `\"`, `"`)
	inner = strings.ReplaceAll(inner, `'`, `\'`)
	return "'" + inner + "'"
}
