-- Schema-only dump for release v0.6.6 (migration version 46).
-- Generated by `cd backend && go run ./cmd/genschema -tag v0.6.6 -version 46`
-- from the embedded migration chain (frozen and append-only, so migrations
-- 000001..000046 are byte-identical to the tagged release's own files).
-- FROZEN: a historical schema never changes retroactively -- see README.md.
-- Do not hand-edit; regenerate instead.

PRAGMA foreign_keys=OFF;

CREATE TABLE schema_migrations (version uint64,dirty bool);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_reset_token_hash TEXT,
    password_reset_expires_at DATETIME,
    password_reset_requested_at DATETIME,
    language TEXT DEFAULT 'en',
    is_admin INTEGER DEFAULT 0,
    date_format TEXT DEFAULT 'eu',
    oidc_subject TEXT,
    oidc_provider TEXT,
    enabled_contact_fields TEXT DEFAULT NULL,
    token_version INTEGER NOT NULL DEFAULT 0
, notify_ntfy INTEGER NOT NULL DEFAULT 0, notify_gotify INTEGER NOT NULL DEFAULT 0, notify_push INTEGER NOT NULL DEFAULT 0, self_contact_vcard_uid TEXT, totp_secret_encrypted TEXT, totp_enabled INTEGER NOT NULL DEFAULT 0, totp_confirmed_at DATETIME);

CREATE TABLE contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    firstname TEXT NOT NULL COLLATE NOCASE,
    lastname TEXT COLLATE NOCASE,
    nickname TEXT COLLATE NOCASE,
    gender TEXT,
    email TEXT COLLATE NOCASE,
    phone TEXT,
    birthday TEXT,
    photo TEXT,
    photo_thumbnail TEXT,
    address TEXT,
    how_we_met TEXT,
    work_information TEXT,
    contact_information TEXT,
    circles TEXT,
    user_id INTEGER,
    vcard_uid TEXT,
    vcard_extra TEXT,
    etag TEXT,
    archived INTEGER DEFAULT 0 NOT NULL,
    emails TEXT DEFAULT '[]',
    phones TEXT DEFAULT '[]',
    addresses TEXT DEFAULT '[]',
    urls TEXT DEFAULT '[]',
    impps TEXT DEFAULT '[]',
    prefix TEXT DEFAULT '',
    middle_name TEXT DEFAULT '',
    suffix TEXT DEFAULT '',
    organization TEXT DEFAULT '',
    department TEXT DEFAULT '',
    job_title TEXT DEFAULT '',
    role TEXT DEFAULT '',
    anniversary TEXT DEFAULT '',
    card TEXT DEFAULT '{}',
    crm TEXT DEFAULT '{}',
    passthrough TEXT DEFAULT '{}',
    fn TEXT DEFAULT '',
    org TEXT DEFAULT ''
, addresses_flat TEXT NOT NULL DEFAULT '', phones_normalized TEXT NOT NULL DEFAULT '', sort_name TEXT NOT NULL DEFAULT '', is_favorite INTEGER NOT NULL DEFAULT 0, revision INTEGER NOT NULL DEFAULT 1);

CREATE TABLE activities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    title TEXT NOT NULL,
    description TEXT,
    location TEXT,
    date DATETIME NOT NULL,
    user_id INTEGER,
    uuid TEXT,
    type TEXT,
    external_ref TEXT,
    etag TEXT
, revision INTEGER NOT NULL DEFAULT 1);

CREATE TABLE activity_contacts (
    activity_id INTEGER NOT NULL,
    contact_id INTEGER NOT NULL,
    PRIMARY KEY (activity_id, contact_id),
    FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE,
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE
);

CREATE TABLE api_tokens (
    id           INTEGER  PRIMARY KEY AUTOINCREMENT,
    created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted_at   DATETIME,
    user_id      INTEGER  NOT NULL,
    name         TEXT     NOT NULL,
    token_hash   TEXT     NOT NULL UNIQUE,
    last_used_at DATETIME,
    revoked_at   DATETIME,
    expires_at   DATETIME,
    scope        TEXT     NOT NULL DEFAULT 'full',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    content TEXT NOT NULL,
    date DATETIME NOT NULL,
    contact_id INTEGER,
    user_id INTEGER, revision INTEGER NOT NULL DEFAULT 1, etag TEXT,
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE reminders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    message TEXT NOT NULL,
    by_mail INTEGER DEFAULT 0,
    remind_at DATETIME NOT NULL,
    recurrence TEXT NOT NULL,
    reoccur_from_completion INTEGER DEFAULT 1,
    last_sent DATETIME,
    contact_id INTEGER NOT NULL,
    completed BOOLEAN DEFAULT false NOT NULL,
    user_id INTEGER,
    email_sent BOOLEAN DEFAULT FALSE NOT NULL,
    life_event_id TEXT, revision INTEGER NOT NULL DEFAULT 1, etag TEXT,
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE reminder_completions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    reminder_id INTEGER,
    contact_id INTEGER NOT NULL,
    message TEXT NOT NULL,
    completed_at DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE
);

CREATE TABLE job_executions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_name TEXT UNIQUE NOT NULL,
    last_run_at DATETIME NOT NULL,
    locked_at DATETIME,
    locked_by TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME
);

CREATE TABLE carddav_sync (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL UNIQUE,
    sync_token TEXT NOT NULL,
    last_modified DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE calendar_subscriptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    password_encrypted TEXT NOT NULL DEFAULT '',
    sync_enabled INTEGER NOT NULL DEFAULT 1,
    past_days INTEGER NOT NULL DEFAULT 5,
    future_days INTEGER NOT NULL DEFAULT 10,
    last_synced_at DATETIME,
    last_sync_status TEXT NOT NULL DEFAULT '',
    last_sync_error TEXT NOT NULL DEFAULT '', last_attempt_at DATETIME, last_success_at DATETIME, last_failure_at DATETIME, consecutive_failures INTEGER NOT NULL DEFAULT 0, incident_first_failure_at DATETIME, last_run_duration_ms INTEGER, last_run_stats TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE calendar_event_links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME, updated_at DATETIME,
    subscription_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    uid TEXT NOT NULL,
    activity_id INTEGER NOT NULL,
    content_hash TEXT NOT NULL, remote_etag TEXT, remote_path TEXT,
    FOREIGN KEY (subscription_id) REFERENCES calendar_subscriptions(id) ON DELETE CASCADE
);

CREATE TABLE contact_subscriptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    password_encrypted TEXT NOT NULL DEFAULT '',
    sync_enabled INTEGER NOT NULL DEFAULT 1,
    sync_token TEXT NOT NULL DEFAULT '',
    last_synced_at DATETIME,
    last_sync_status TEXT NOT NULL DEFAULT '',
    last_sync_error TEXT NOT NULL DEFAULT '', last_attempt_at DATETIME, last_success_at DATETIME, last_failure_at DATETIME, consecutive_failures INTEGER NOT NULL DEFAULT 0, incident_first_failure_at DATETIME, last_run_duration_ms INTEGER, last_run_stats TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE contact_sync_links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME, updated_at DATETIME,
    subscription_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    href TEXT NOT NULL,
    contact_id INTEGER NOT NULL,
    etag TEXT NOT NULL DEFAULT '',
    content_hash TEXT NOT NULL, synced_values TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (subscription_id) REFERENCES contact_subscriptions(id) ON DELETE CASCADE
);

CREATE TABLE relationship_edges (
    id TEXT PRIMARY KEY,
    created_at DATETIME, updated_at DATETIME,
    user_id INTEGER NOT NULL,
    source_id TEXT NOT NULL,
    target_id TEXT NOT NULL,
    type TEXT NOT NULL,
    directional INTEGER NOT NULL DEFAULT 0,
    metadata TEXT,
    source TEXT NOT NULL,
    confidence REAL NOT NULL DEFAULT 1,
    status TEXT NOT NULL,
    sensitivity TEXT NOT NULL DEFAULT 'normal',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE households (
    id TEXT PRIMARY KEY,
    created_at DATETIME, updated_at DATETIME,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    address TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE household_members (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME, updated_at DATETIME,
    household_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    member_vcard_uid TEXT NOT NULL,
    role TEXT,
    since TEXT,
    until TEXT,
    FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE
);

CREATE TABLE circles (
    id TEXT PRIMARY KEY,
    created_at DATETIME, updated_at DATETIME,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE circle_members (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME, updated_at DATETIME,
    circle_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    member_vcard_uid TEXT NOT NULL,
    FOREIGN KEY (circle_id) REFERENCES circles(id) ON DELETE CASCADE
);

CREATE TABLE tags (
    id TEXT PRIMARY KEY,
    created_at DATETIME, updated_at DATETIME,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE contact_tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME, updated_at DATETIME,
    tag_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    contact_vcard_uid TEXT NOT NULL,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

CREATE TABLE life_events (
    id TEXT PRIMARY KEY,
    created_at DATETIME, updated_at DATETIME,
    user_id INTEGER NOT NULL,
    entity_id TEXT NOT NULL,
    type TEXT,
    date TEXT,
    description TEXT,
    source TEXT,
    related_entity_ids TEXT,
    deleted_at DATETIME,
    remind INTEGER NOT NULL DEFAULT 0,
    etag TEXT, category TEXT, revision INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE field_definitions (
    id TEXT PRIMARY KEY,
    created_at DATETIME, updated_at DATETIME,
    user_id INTEGER NOT NULL,
    label TEXT NOT NULL,
    key TEXT NOT NULL,
    target TEXT NOT NULL,
    type TEXT NOT NULL,
    constraints TEXT,
    projection TEXT NOT NULL DEFAULT 'internal-only',
    sensitivity TEXT NOT NULL DEFAULT 'normal',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE field_values (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME, updated_at DATETIME,
    field_definition_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    entity_id TEXT NOT NULL,
    value TEXT,
    FOREIGN KEY (field_definition_id) REFERENCES field_definitions(id) ON DELETE CASCADE
);

CREATE TABLE preferences (
    id TEXT PRIMARY KEY,
    created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    entity_id TEXT NOT NULL,
    category TEXT NOT NULL,
    key TEXT,
    value TEXT NOT NULL,
    source TEXT,
    confidence REAL,
    last_confirmed DATETIME,
    sensitivity TEXT NOT NULL DEFAULT 'normal', notes TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE webhooks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    events TEXT NOT NULL DEFAULT '[]',
    secret TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE webhook_deliveries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
    webhook_id INTEGER NOT NULL,
    event_type TEXT NOT NULL,
    payload TEXT NOT NULL,
    status_code INTEGER,
    error TEXT,
    attempts INTEGER NOT NULL DEFAULT 1,
    next_retry_at DATETIME,
    FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE
);

CREATE TABLE cadence_policies (
    id TEXT PRIMARY KEY,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    entity_id TEXT NOT NULL,
    target_interval_days INTEGER NOT NULL,
    qualifying_types TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE conversation_agenda (
    id TEXT PRIMARY KEY,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    entity_id TEXT NOT NULL,
    content TEXT NOT NULL,
    reference_url TEXT,
    discussed_at DATETIME,
    activity_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE gifts (
    id TEXT PRIMARY KEY,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    entity_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'idea',
    occasion TEXT,
    description TEXT NOT NULL,
    date DATETIME,
    value_cents INTEGER,
    currency TEXT,
    life_event_id TEXT,
    activity_id INTEGER, url TEXT, notes TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE external_identities (
    id TEXT PRIMARY KEY,
    created_at DATETIME,
    updated_at DATETIME,
    user_id INTEGER NOT NULL,
    entity_id TEXT NOT NULL,
    system TEXT NOT NULL,
    external_id TEXT NOT NULL,
    url TEXT,
    metadata TEXT,
    sync_status TEXT NOT NULL DEFAULT 'idle',
    last_synced_at DATETIME,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE external_activities (
    id TEXT PRIMARY KEY,
    created_at DATETIME,
    updated_at DATETIME,
    user_id INTEGER NOT NULL,
    entity_id TEXT NOT NULL,
    source_system TEXT NOT NULL,
    external_id TEXT NOT NULL,
    type TEXT NOT NULL,
    occurred_at DATETIME NOT NULL,
    payload TEXT,
    provenance TEXT NOT NULL DEFAULT 'external',
    sync_state TEXT NOT NULL DEFAULT 'synced',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE immich_configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    base_url TEXT NOT NULL,
    api_key_encrypted TEXT NOT NULL DEFAULT '',
    sync_enabled INTEGER NOT NULL DEFAULT 1,
    last_synced_at DATETIME,
    last_sync_status TEXT NOT NULL DEFAULT '',
    last_sync_error TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE VIRTUAL TABLE notes_fts USING fts5(
    content,
    user_id UNINDEXED
);

CREATE VIRTUAL TABLE activities_fts USING fts5(
    title, description, location,
    user_id UNINDEXED
);

CREATE TABLE contact_shares (
    id TEXT PRIMARY KEY,
    created_at DATETIME,
    updated_at DATETIME,
    from_user_id INTEGER NOT NULL,
    to_user_id INTEGER NOT NULL,
    contact_display_name TEXT,
    payload TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    responded_at DATETIME,
    FOREIGN KEY (from_user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (to_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE link_field_types (
    id TEXT PRIMARY KEY,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    protocol TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL,
    icon TEXT,
    is_default BOOLEAN NOT NULL DEFAULT 0,
    position INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE notification_configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    ntfy_url TEXT NOT NULL DEFAULT '',
    ntfy_topic TEXT NOT NULL DEFAULT '',
    gotify_url TEXT NOT NULL DEFAULT '',
    gotify_token_encrypted TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE push_subscriptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    user_id INTEGER NOT NULL,
    endpoint TEXT NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    device_label TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE notification_deliveries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    reminder_id INTEGER NOT NULL,
    channel TEXT NOT NULL CHECK (channel IN ('email', 'ntfy', 'gotify', 'push')),
    sent_at DATETIME,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
    error TEXT,
    FOREIGN KEY (reminder_id) REFERENCES reminders(id) ON DELETE CASCADE
);

CREATE TABLE server_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE dismissed_household_suggestions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    user_id INTEGER NOT NULL,
    address_hash TEXT NOT NULL,
    member_hash TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE attachments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    contact_vcard_uid TEXT NOT NULL,
    stored_name TEXT NOT NULL,
    original_name TEXT NOT NULL,
    content_type TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE device_registrations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    user_id INTEGER NOT NULL,
    token TEXT NOT NULL,
    client TEXT NOT NULL CHECK (client IN ('fcm', 'apns')),
    device_label TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE VIRTUAL TABLE contacts_fts USING fts5(
    firstname, lastname, nickname, email, phone, org, addresses_flat, phones_normalized,
    user_id UNINDEXED
);

CREATE TABLE dismissed_duplicate_pairs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    user_id INTEGER NOT NULL,
    uid_low TEXT NOT NULL,
    uid_high TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE recovery_codes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    user_id INTEGER NOT NULL,
    code_hash TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE paperless_configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    base_url TEXT NOT NULL,
    api_token_encrypted TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE seafile_configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    base_url TEXT NOT NULL,
    api_token_encrypted TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE webdav_configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    user_id INTEGER NOT NULL,
    base_url TEXT NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    app_password_encrypted TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE reach_out_suggestions (
    id TEXT PRIMARY KEY,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    user_id INTEGER NOT NULL,
    contact_vcard_uid TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('organization', 'title', 'address')),
    old_value TEXT NOT NULL DEFAULT '',
    new_value TEXT NOT NULL DEFAULT '',
    audit_event_id INTEGER NOT NULL,
    reminder_id INTEGER,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'dismissed'))
);

CREATE TABLE reach_out_cursors (
    user_id INTEGER PRIMARY KEY,
    last_audit_event_id INTEGER NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL
);

CREATE TABLE contact_sync_conflicts (
    id TEXT PRIMARY KEY,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    user_id INTEGER NOT NULL,
    subscription_id INTEGER NOT NULL,
    contact_id INTEGER NOT NULL,
    field TEXT NOT NULL,
    local_value TEXT NOT NULL DEFAULT '',
    remote_value TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'dismissed'))
);

CREATE TABLE data_encryption_keys (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    key_id      TEXT    NOT NULL UNIQUE,
    wrapped_dek BLOB    NOT NULL,
    created_at  DATETIME NOT NULL
);

CREATE TABLE "audit_events" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    operation TEXT NOT NULL CHECK (operation IN (
        'create', 'update', 'delete',
        'login', 'login_failed', 'register',
        'password_change', 'password_reset', 'password_reset_requested',
        'totp_enable', 'totp_disable', 'recovery_regenerate',
        'revoke', 'role_change', 'two_factor_admin_reset'
    )),
    user_id INTEGER NOT NULL,
    before_snapshot TEXT,
    hash TEXT NOT NULL DEFAULT '',
    prev_hash TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE operational_check_results (
    check_name TEXT PRIMARY KEY,
    status     TEXT NOT NULL CHECK (status IN ('ok', 'failed', 'error')),
    detail     TEXT NOT NULL DEFAULT '',
    checked_at DATETIME NOT NULL,
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE system_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME NOT NULL,
    occurred_at DATETIME NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN (
        'application_started', 'application_stopped',
        'migration_started', 'migration_completed', 'migration_failed',
        'job_started', 'job_completed', 'job_failed',
        'sync_started', 'sync_completed', 'sync_failed',
        'notification_sent', 'notification_failed',
        'backup_completed', 'backup_failed', 'restore_test_completed',
        'integration_failed'
    )),
    severity TEXT NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warn', 'error')),
    component TEXT NOT NULL DEFAULT '',
    operation TEXT NOT NULL DEFAULT '',
    duration_ms INTEGER,
    result TEXT CHECK (result IS NULL OR result IN ('success', 'failure', 'skipped')),
    correlation_id TEXT NOT NULL DEFAULT '',
    error TEXT NOT NULL DEFAULT '',
    detail TEXT NOT NULL DEFAULT '',
    user_id INTEGER
);

CREATE TABLE alert_states (
    condition_key    TEXT PRIMARY KEY,
    state            TEXT NOT NULL CHECK (state IN ('ok', 'alerting')),
    since            DATETIME NOT NULL,
    detail           TEXT NOT NULL DEFAULT '',
    failure_count    INTEGER NOT NULL DEFAULT 0,
    last_notified_at DATETIME,
    created_at       DATETIME,
    updated_at       DATETIME
);

CREATE TABLE job_runs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at      DATETIME NOT NULL,
    job_name        TEXT NOT NULL,
    trigger         TEXT NOT NULL DEFAULT 'scheduled'
                      CHECK (trigger IN ('scheduled', 'initial', 'manual')),
    started_at      DATETIME NOT NULL,
    finished_at     DATETIME NOT NULL,
    duration_ms     INTEGER NOT NULL,
    result          TEXT NOT NULL CHECK (result IN ('success', 'failure', 'skipped')),
    error           TEXT NOT NULL DEFAULT '',
    items_processed INTEGER,
    detail          TEXT NOT NULL DEFAULT '',
    correlation_id  TEXT NOT NULL DEFAULT ''
);

CREATE TABLE storage_samples (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    taken_at            DATETIME NOT NULL,
    database_bytes      INTEGER NOT NULL,
    fs_used_bytes       INTEGER NOT NULL,
    fs_total_bytes      INTEGER NOT NULL,
    photo_dir_bytes     INTEGER NOT NULL DEFAULT 0,
    attachment_dir_bytes INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE import_source_links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME,
    updated_at DATETIME,
    user_id INTEGER NOT NULL,
    system TEXT NOT NULL,
    external_id TEXT NOT NULL,
    entity_kind TEXT NOT NULL,
    entity_uid TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE "import_runs" (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id         INTEGER NOT NULL,
    format          TEXT NOT NULL CHECK (format IN ('csv', 'vcf', 'jscontact', 'records', 'monica', 'meerkat')),
    total_processed INTEGER NOT NULL DEFAULT 0,
    created         INTEGER NOT NULL DEFAULT 0,
    updated         INTEGER NOT NULL DEFAULT 0,
    skipped         INTEGER NOT NULL DEFAULT 0,
    error_count     INTEGER NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL
);

CREATE UNIQUE INDEX version_unique ON schema_migrations (version);

CREATE INDEX idx_users_deleted_at ON users(deleted_at);

CREATE INDEX idx_users_email ON users(email);

CREATE UNIQUE INDEX idx_users_oidc_subject ON users(oidc_subject, oidc_provider)
    WHERE oidc_subject IS NOT NULL;

CREATE INDEX idx_users_password_reset_token_hash ON users(password_reset_token_hash);

CREATE INDEX idx_users_username ON users(username);

CREATE INDEX idx_contacts_deleted_at ON contacts(deleted_at);

CREATE INDEX idx_contacts_email ON contacts(email COLLATE NOCASE);

CREATE INDEX idx_contacts_feed ON contacts(user_id, updated_at, id);

CREATE INDEX idx_contacts_firstname ON contacts(firstname COLLATE NOCASE);

CREATE INDEX idx_contacts_lastname ON contacts(lastname COLLATE NOCASE);

CREATE INDEX idx_contacts_user_id ON contacts(user_id);

CREATE UNIQUE INDEX idx_contacts_vcard_uid_user
    ON contacts(user_id, vcard_uid)
    WHERE vcard_uid IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX idx_activities_date ON activities(date);

CREATE INDEX idx_activities_deleted_at ON activities(deleted_at);

CREATE INDEX idx_activities_feed ON activities(user_id, updated_at, id);

CREATE INDEX idx_activities_user_id ON activities(user_id);

CREATE INDEX idx_activities_uuid ON activities(uuid);

CREATE INDEX idx_activity_contacts_activity_id ON activity_contacts(activity_id);

CREATE INDEX idx_activity_contacts_contact_id ON activity_contacts(contact_id);

CREATE INDEX idx_api_tokens_expires_at ON api_tokens(expires_at);

CREATE INDEX idx_api_tokens_token_hash ON api_tokens(token_hash);

CREATE INDEX idx_api_tokens_user_id ON api_tokens(user_id);

CREATE INDEX idx_notes_contact_id ON notes(contact_id);

CREATE INDEX idx_notes_date ON notes(date);

CREATE INDEX idx_notes_deleted_at ON notes(deleted_at);

CREATE INDEX idx_notes_feed ON notes(user_id, updated_at, id);

CREATE INDEX idx_notes_user_id ON notes(user_id);

CREATE INDEX idx_reminders_contact_id ON reminders(contact_id);

CREATE INDEX idx_reminders_deleted_at ON reminders(deleted_at);

CREATE INDEX idx_reminders_life_event_id ON reminders(life_event_id);

CREATE INDEX idx_reminders_remind_at ON reminders(remind_at);

CREATE INDEX idx_reminders_user_id ON reminders(user_id);

CREATE INDEX idx_reminder_completions_contact_id ON reminder_completions(contact_id);

CREATE INDEX idx_reminder_completions_user_id ON reminder_completions(user_id);

CREATE INDEX idx_job_executions_deleted_at ON job_executions(deleted_at);

CREATE UNIQUE INDEX idx_job_executions_job_name ON job_executions(job_name);

CREATE INDEX idx_carddav_sync_user ON carddav_sync(user_id);

CREATE INDEX idx_calendar_subscriptions_deleted_at ON calendar_subscriptions(deleted_at);

CREATE INDEX idx_calendar_subscriptions_user_id ON calendar_subscriptions(user_id);

CREATE INDEX idx_calendar_event_links_activity_id ON calendar_event_links(activity_id);

CREATE UNIQUE INDEX idx_calendar_event_links_sub_uid ON calendar_event_links(subscription_id, uid);

CREATE INDEX idx_calendar_event_links_user_id ON calendar_event_links(user_id);

CREATE INDEX idx_contact_subscriptions_deleted_at ON contact_subscriptions(deleted_at);

CREATE INDEX idx_contact_subscriptions_user_id ON contact_subscriptions(user_id);

CREATE INDEX idx_contact_sync_links_contact_id ON contact_sync_links(contact_id);

CREATE UNIQUE INDEX idx_contact_sync_links_sub_href ON contact_sync_links(subscription_id, href);

CREATE INDEX idx_contact_sync_links_user_id ON contact_sync_links(user_id);

CREATE INDEX idx_relationship_edges_feed ON relationship_edges(user_id, updated_at, id);

CREATE INDEX idx_relationship_edges_sensitivity ON relationship_edges(sensitivity);

CREATE INDEX idx_relationship_edges_source_id ON relationship_edges(source_id);

CREATE INDEX idx_relationship_edges_status ON relationship_edges(status);

CREATE INDEX idx_relationship_edges_target_id ON relationship_edges(target_id);

CREATE INDEX idx_relationship_edges_type ON relationship_edges(type);

CREATE INDEX idx_relationship_edges_user_id ON relationship_edges(user_id);

CREATE INDEX idx_households_feed ON households(user_id, updated_at, id);

CREATE INDEX idx_households_user_id ON households(user_id);

CREATE UNIQUE INDEX idx_household_members_household_member
    ON household_members(household_id, member_vcard_uid);

CREATE INDEX idx_household_members_member_vcard_uid ON household_members(member_vcard_uid);

CREATE INDEX idx_household_members_user_id ON household_members(user_id);

CREATE INDEX idx_circles_feed ON circles(user_id, updated_at, id);

CREATE INDEX idx_circles_user_id ON circles(user_id);

CREATE UNIQUE INDEX idx_circle_members_circle_member
    ON circle_members(circle_id, member_vcard_uid);

CREATE INDEX idx_circle_members_member_vcard_uid ON circle_members(member_vcard_uid);

CREATE INDEX idx_circle_members_user_id ON circle_members(user_id);

CREATE INDEX idx_tags_feed ON tags(user_id, updated_at, id);

CREATE INDEX idx_tags_user_id ON tags(user_id);

CREATE UNIQUE INDEX idx_contact_tags_tag_contact
    ON contact_tags(tag_id, contact_vcard_uid);

CREATE INDEX idx_contact_tags_contact_vcard_uid ON contact_tags(contact_vcard_uid);

CREATE INDEX idx_contact_tags_user_id ON contact_tags(user_id);

CREATE INDEX idx_life_events_deleted_at ON life_events(deleted_at);

CREATE INDEX idx_life_events_entity_id ON life_events(entity_id);

CREATE INDEX idx_life_events_feed ON life_events(user_id, updated_at, id);

CREATE INDEX idx_life_events_user_id ON life_events(user_id);

CREATE INDEX idx_field_definitions_feed ON field_definitions(user_id, updated_at, id);

CREATE INDEX idx_field_definitions_sensitivity ON field_definitions(sensitivity);

CREATE UNIQUE INDEX idx_field_definitions_user_key ON field_definitions(user_id, key);

CREATE UNIQUE INDEX idx_field_values_definition_entity
    ON field_values(field_definition_id, entity_id);

CREATE INDEX idx_field_values_entity_id ON field_values(entity_id);

CREATE INDEX idx_field_values_user_id ON field_values(user_id);

CREATE INDEX idx_preferences_entity_id ON preferences(entity_id);

CREATE INDEX idx_preferences_feed ON preferences(user_id, updated_at, id);

CREATE INDEX idx_preferences_sensitivity ON preferences(sensitivity);

CREATE INDEX idx_preferences_user_id ON preferences(user_id);

CREATE INDEX idx_webhooks_deleted_at ON webhooks(deleted_at);

CREATE INDEX idx_webhooks_user_id ON webhooks(user_id);

CREATE INDEX idx_webhook_deliveries_next_retry_at ON webhook_deliveries(next_retry_at);

CREATE INDEX idx_webhook_deliveries_webhook_id ON webhook_deliveries(webhook_id);

CREATE INDEX idx_cadence_policies_deleted_at ON cadence_policies(deleted_at);

CREATE INDEX idx_cadence_policies_entity_id ON cadence_policies(entity_id);

CREATE INDEX idx_cadence_policies_feed ON cadence_policies(user_id, updated_at, id);

CREATE INDEX idx_cadence_policies_user_id ON cadence_policies(user_id);

CREATE UNIQUE INDEX idx_cadence_policies_user_entity
    ON cadence_policies(user_id, entity_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_conversation_agenda_deleted_at ON conversation_agenda(deleted_at);

CREATE INDEX idx_conversation_agenda_entity_id ON conversation_agenda(entity_id);

CREATE INDEX idx_conversation_agenda_feed ON conversation_agenda(user_id, updated_at, id);

CREATE INDEX idx_conversation_agenda_user_id ON conversation_agenda(user_id);

CREATE INDEX idx_conversation_agenda_discussed_at ON conversation_agenda(discussed_at);

CREATE INDEX idx_conversation_agenda_activity_id ON conversation_agenda(activity_id);

CREATE INDEX idx_gifts_deleted_at ON gifts(deleted_at);

CREATE INDEX idx_gifts_entity_id ON gifts(entity_id);

CREATE INDEX idx_gifts_feed ON gifts(user_id, updated_at, id);

CREATE INDEX idx_gifts_user_id ON gifts(user_id);

CREATE INDEX idx_gifts_status ON gifts(status);

CREATE INDEX idx_gifts_date ON gifts(date);

CREATE INDEX idx_gifts_life_event_id ON gifts(life_event_id);

CREATE INDEX idx_gifts_activity_id ON gifts(activity_id);

CREATE UNIQUE INDEX idx_external_identities_system_ext_user
    ON external_identities(system, external_id, user_id);

CREATE INDEX idx_external_identities_entity_id ON external_identities(entity_id);

CREATE INDEX idx_external_identities_system ON external_identities(system);

CREATE INDEX idx_external_identities_user_id ON external_identities(user_id);

CREATE UNIQUE INDEX idx_external_activities_system_ext_user
    ON external_activities(source_system, external_id, user_id);

CREATE INDEX idx_external_activities_entity_id ON external_activities(entity_id);

CREATE INDEX idx_external_activities_occurred_at ON external_activities(occurred_at);

CREATE INDEX idx_external_activities_type ON external_activities(type);

CREATE INDEX idx_external_activities_user_id ON external_activities(user_id);

CREATE UNIQUE INDEX idx_immich_configs_user_id ON immich_configs(user_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_contact_shares_to_user_feed ON contact_shares(to_user_id, updated_at, id);

CREATE INDEX idx_contact_shares_from_user_feed ON contact_shares(from_user_id, updated_at, id);

CREATE INDEX idx_contact_shares_status ON contact_shares(status);

CREATE INDEX idx_link_field_types_deleted_at ON link_field_types(deleted_at);

CREATE INDEX idx_link_field_types_user_id ON link_field_types(user_id);

CREATE UNIQUE INDEX idx_link_field_types_user_name
    ON link_field_types(user_id, name)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX idx_notification_configs_user_id ON notification_configs(user_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_push_subscriptions_user_id ON push_subscriptions(user_id);

CREATE INDEX idx_notification_deliveries_reminder_id ON notification_deliveries(reminder_id);

CREATE INDEX idx_notification_deliveries_channel ON notification_deliveries(channel);

CREATE UNIQUE INDEX idx_dismissed_household_suggestions_unique
    ON dismissed_household_suggestions(user_id, address_hash, member_hash);

CREATE INDEX idx_dismissed_household_suggestions_user_id
    ON dismissed_household_suggestions(user_id);

CREATE INDEX idx_attachments_contact ON attachments(contact_vcard_uid);

CREATE INDEX idx_attachments_user ON attachments(user_id);

CREATE UNIQUE INDEX idx_device_registrations_client_token
    ON device_registrations(client, token);

CREATE INDEX idx_device_registrations_user_id ON device_registrations(user_id);

CREATE INDEX idx_contacts_sort_name ON contacts(user_id, sort_name, id);

CREATE UNIQUE INDEX idx_dismissed_duplicate_pairs_unique
    ON dismissed_duplicate_pairs(user_id, uid_low, uid_high);

CREATE INDEX idx_dismissed_duplicate_pairs_user_id
    ON dismissed_duplicate_pairs(user_id);

CREATE UNIQUE INDEX idx_recovery_codes_user_code ON recovery_codes(user_id, code_hash);

CREATE INDEX idx_recovery_codes_user_id ON recovery_codes(user_id);

CREATE UNIQUE INDEX idx_paperless_configs_user_id ON paperless_configs(user_id)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX idx_seafile_configs_user_id ON seafile_configs(user_id)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX idx_webdav_configs_user_id ON webdav_configs(user_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_reach_out_suggestions_user_status ON reach_out_suggestions(user_id, status);

CREATE INDEX idx_reach_out_suggestions_contact ON reach_out_suggestions(contact_vcard_uid);

CREATE INDEX idx_reach_out_suggestions_reminder ON reach_out_suggestions(reminder_id);

CREATE INDEX idx_contact_sync_conflicts_user_status ON contact_sync_conflicts(user_id, status);

CREATE INDEX idx_contact_sync_conflicts_contact ON contact_sync_conflicts(contact_id);

CREATE INDEX idx_contact_sync_conflicts_subscription ON contact_sync_conflicts(subscription_id);

CREATE INDEX idx_audit_events_entity ON audit_events(entity_type, entity_id);

CREATE INDEX idx_audit_events_user ON audit_events(user_id);

CREATE INDEX idx_audit_events_created ON audit_events(created_at);

CREATE INDEX idx_system_events_occurred_at ON system_events(occurred_at);

CREATE INDEX idx_system_events_correlation_id ON system_events(correlation_id);

CREATE INDEX idx_system_events_component ON system_events(component);

CREATE INDEX idx_system_events_severity ON system_events(severity);

CREATE INDEX idx_system_events_event_type ON system_events(event_type);

CREATE INDEX idx_job_runs_started_at ON job_runs(started_at);

CREATE INDEX idx_job_runs_job_name_started_at ON job_runs(job_name, started_at);

CREATE INDEX idx_job_runs_correlation_id ON job_runs(correlation_id);

CREATE INDEX idx_storage_samples_taken_at ON storage_samples(taken_at);

CREATE UNIQUE INDEX idx_import_source_links_system_ext_user
    ON import_source_links(system, external_id, user_id);

CREATE INDEX idx_import_source_links_entity_uid ON import_source_links(entity_uid);

CREATE INDEX idx_import_source_links_user_id ON import_source_links(user_id);

CREATE INDEX idx_import_runs_user ON import_runs(user_id, created_at);

CREATE TRIGGER notes_fts_ai AFTER INSERT ON notes BEGIN
    INSERT INTO notes_fts(rowid, user_id, content) VALUES (new.id, new.user_id, new.content);
END;

CREATE TRIGGER notes_fts_ad AFTER DELETE ON notes BEGIN
    DELETE FROM notes_fts WHERE rowid = old.id;
END;

CREATE TRIGGER notes_fts_au AFTER UPDATE ON notes BEGIN
    DELETE FROM notes_fts WHERE rowid = old.id;
    INSERT INTO notes_fts(rowid, user_id, content)
    SELECT new.id, new.user_id, new.content
    WHERE new.deleted_at IS NULL;
END;

CREATE TRIGGER activities_fts_ai AFTER INSERT ON activities BEGIN
    INSERT INTO activities_fts(rowid, user_id, title, description, location)
    VALUES (new.id, new.user_id, new.title, new.description, new.location);
END;

CREATE TRIGGER activities_fts_ad AFTER DELETE ON activities BEGIN
    DELETE FROM activities_fts WHERE rowid = old.id;
END;

CREATE TRIGGER activities_fts_au AFTER UPDATE ON activities BEGIN
    DELETE FROM activities_fts WHERE rowid = old.id;
    INSERT INTO activities_fts(rowid, user_id, title, description, location)
    SELECT new.id, new.user_id, new.title, new.description, new.location
    WHERE new.deleted_at IS NULL;
END;

CREATE TRIGGER contacts_fts_ai AFTER INSERT ON contacts BEGIN
    INSERT INTO contacts_fts(rowid, user_id, firstname, lastname, nickname, email, phone, org, addresses_flat, phones_normalized)
    VALUES (new.id, new.user_id, new.firstname, new.lastname, new.nickname, new.email, new.phone, new.org, new.addresses_flat, new.phones_normalized);
END;

CREATE TRIGGER contacts_fts_ad AFTER DELETE ON contacts BEGIN
    DELETE FROM contacts_fts WHERE rowid = old.id;
END;

CREATE TRIGGER contacts_fts_au AFTER UPDATE ON contacts BEGIN
    DELETE FROM contacts_fts WHERE rowid = old.id;
    INSERT INTO contacts_fts(rowid, user_id, firstname, lastname, nickname, email, phone, org, addresses_flat, phones_normalized)
    SELECT new.id, new.user_id, new.firstname, new.lastname, new.nickname, new.email, new.phone, new.org, new.addresses_flat, new.phones_normalized
    WHERE new.deleted_at IS NULL;
END;

CREATE TRIGGER audit_events_no_update
BEFORE UPDATE ON audit_events
BEGIN
    SELECT RAISE(ABORT, 'audit_events is append-only: UPDATE is not allowed');
END;

INSERT INTO schema_migrations (version, dirty) VALUES (46, 0);
