package differential

// TEST-08 divergence-pin registry for the JSContact-calcard differential leg.
// See registerVCardPins for the policy: pins document reference-side
// divergences with drift detection; confirmed our-side bugs are fixed, never
// pinned (the RFC 9553 created/updated UTCDateTime-string fix in the
// jscontact adapter, found by this very suite, is the canonical example).
//
// The re-emit leg (ours -> reference) is near-clean: our JSContact exporter's
// output is read back semantically-equivalently by calcard for everything
// JSContact can represent, with only the format-inherent scalar/set collapses
// pinned. The conversion leg (reference -> ours) documents calcard's RFC 9555
// vCard->JSContact conversion behavior — losses the independent implementation
// makes that our adapter does not.
func registerJSContactPins() {
	if jscontactPinsRegistered {
		return
	}
	jscontactPinsRegistered = true
	checkPin(DivergencePin{CorpusID: "fixture/test07_duplicate_keywords", Format: "jscontact", Dir: "ours->reference", Concepts: []string{"keywords"}, Reason: "RFC 9553 keywords is a boolean set on the wire; duplicate neutral keywords collapse (calcard re-emit confirms the set semantics)"})
	checkPin(DivergencePin{CorpusID: "fixture/test07_multi_grammatical_gender", Format: "jscontact", Dir: "ours->reference", Concepts: []string{"gramgender"}, Reason: "RFC 9553 speakToAs.grammaticalGender is scalar; multiple GRAMGENDER entries (RFC 9554, per LANGUAGE) collapse to one, and calcard confirms JSContact cannot hold more"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0009", Format: "jscontact", Dir: "ours->reference", Concepts: []string{"gramgender"}, Reason: "RFC 9553 speakToAs.grammaticalGender is scalar; multiple GRAMGENDER entries (RFC 9554, per LANGUAGE) collapse to one, and calcard confirms JSContact cannot hold more"})
	checkPin(DivergencePin{CorpusID: "fixture/ada", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth", "anniversary.wedding", "impp", "social"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 conversion loses the SERVICE-TYPE (the neutral service field) when moving IMPP into JSContact onlineServices; calcard's RFC 9555 conversion does not preserve SOCIALPROFILE service/user/uri provenance into JSContact onlineServices the way the neutral model records it"})
	checkPin(DivergencePin{CorpusID: "fixture/bob", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth", "anniversary.wedding", "impp"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 conversion loses the SERVICE-TYPE (the neutral service field) when moving IMPP into JSContact onlineServices"})
	checkPin(DivergencePin{CorpusID: "fixture/celine", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth", "name.phonetic"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 conversion drops the phonetic N variant (RFC 9554 ALTID+PHONETIC+SCRIPT) on the way to JSContact"})
	checkPin(DivergencePin{CorpusID: "fixture/eve", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth", "anniversary.wedding"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries"})
	checkPin(DivergencePin{CorpusID: "fixture/frank", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries"})
	checkPin(DivergencePin{CorpusID: "fixture/hugo", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries"})
	checkPin(DivergencePin{CorpusID: "fixture/test07_duplicate_keywords", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"keywords"}, Reason: "RFC 9553 keywords is a boolean set on the wire; duplicate neutral keywords collapse (calcard re-emit confirms the set semantics)"})
	checkPin(DivergencePin{CorpusID: "fixture/test07_multi_grammatical_gender", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"gramgender"}, Reason: "RFC 9553 speakToAs.grammaticalGender is scalar; multiple GRAMGENDER entries (RFC 9554, per LANGUAGE) collapse to one, and calcard confirms JSContact cannot hold more"})
	checkPin(DivergencePin{CorpusID: "fixture/test07_timestamped_birthday", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries"})
	checkPin(DivergencePin{CorpusID: "golden/phonetic-n.v4.vcf", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"name.phonetic"}, Reason: "calcard's RFC 9555 conversion drops the phonetic N variant (RFC 9554 ALTID+PHONETIC+SCRIPT) on the way to JSContact"})
	checkPin(DivergencePin{CorpusID: "golden/socialprofile.v4.vcf", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"social"}, Reason: "calcard's RFC 9555 conversion does not preserve SOCIALPROFILE service/user/uri provenance into JSContact onlineServices the way the neutral model records it"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0000", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth", "impp", "social"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 conversion loses the SERVICE-TYPE (the neutral service field) when moving IMPP into JSContact onlineServices; calcard's RFC 9555 conversion does not preserve SOCIALPROFILE service/user/uri provenance into JSContact onlineServices the way the neutral model records it"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0001", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth", "impp"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 conversion loses the SERVICE-TYPE (the neutral service field) when moving IMPP into JSContact onlineServices"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0002", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.wedding", "impp", "name.phonetic", "social"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 conversion loses the SERVICE-TYPE (the neutral service field) when moving IMPP into JSContact onlineServices; calcard's RFC 9555 conversion drops the phonetic N variant (RFC 9554 ALTID+PHONETIC+SCRIPT) on the way to JSContact; calcard's RFC 9555 conversion does not preserve SOCIALPROFILE service/user/uri provenance into JSContact onlineServices the way the neutral model records it"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0003", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth", "anniversary.death", "anniversary.wedding", "name.phonetic"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 conversion drops the phonetic N variant (RFC 9554 ALTID+PHONETIC+SCRIPT) on the way to JSContact"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0004", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"impp", "social"}, Reason: "calcard's RFC 9555 conversion loses the SERVICE-TYPE (the neutral service field) when moving IMPP into JSContact onlineServices; calcard's RFC 9555 conversion does not preserve SOCIALPROFILE service/user/uri provenance into JSContact onlineServices the way the neutral model records it"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0005", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"social"}, Reason: "calcard's RFC 9555 conversion does not preserve SOCIALPROFILE service/user/uri provenance into JSContact onlineServices the way the neutral model records it"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0007", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth", "impp", "name.phonetic", "social"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 conversion loses the SERVICE-TYPE (the neutral service field) when moving IMPP into JSContact onlineServices; calcard's RFC 9555 conversion drops the phonetic N variant (RFC 9554 ALTID+PHONETIC+SCRIPT) on the way to JSContact; calcard's RFC 9555 conversion does not preserve SOCIALPROFILE service/user/uri provenance into JSContact onlineServices the way the neutral model records it"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0008", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth", "anniversary.death", "impp"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 conversion loses the SERVICE-TYPE (the neutral service field) when moving IMPP into JSContact onlineServices"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0009", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"anniversary.birth", "anniversary.death", "anniversary.place.birth", "anniversary.place.death", "anniversary.wedding", "gramgender", "impp", "name.phonetic", "social"}, Reason: "calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; calcard's RFC 9555 conversion drops BIRTHPLACE/DEATHPLACE from the JSContact output; calcard's RFC 9555 conversion drops BIRTHPLACE/DEATHPLACE from the JSContact output; calcard's RFC 9555 vCard->JSContact conversion re-reads BDAY/ANNIVERSARY/DEATHDATE as partial dates, losing the timestamp-vs-partial distinction the neutral model carries; RFC 9553 speakToAs.grammaticalGender is scalar; multiple GRAMGENDER entries (RFC 9554, per LANGUAGE) collapse to one, and calcard confirms JSContact cannot hold more; calcard's RFC 9555 conversion loses the SERVICE-TYPE (the neutral service field) when moving IMPP into JSContact onlineServices; calcard's RFC 9555 conversion drops the phonetic N variant (RFC 9554 ALTID+PHONETIC+SCRIPT) on the way to JSContact; calcard's RFC 9555 conversion does not preserve SOCIALPROFILE service/user/uri provenance into JSContact onlineServices the way the neutral model records it"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0010", Format: "jscontact", Dir: "reference->ours", Concepts: []string{"impp"}, Reason: "calcard's RFC 9555 conversion loses the SERVICE-TYPE (the neutral service field) when moving IMPP into JSContact onlineServices"})
}
