package differential

// This file is the TEST-08 divergence-pin registry for the vCard-vobject
// differential leg. Every pin records ONE accepted reference-side
// divergence: the concept(s) that differ for one corpus entry, one version,
// one direction, and the written reason. A pin that stops reproducing (the
// reference got fixed, or a corpus card changed so the divergence is gone)
// fails the suite via the drift check in classifyLeg — pins must not rot
// silently.
//
// A divergence confirmed to be OUR bug is fixed, never pinned (the CATEGORIES
// list-escaping fix in vcard3/vcard4, found by this very suite, is the
// canonical example). Everything here is a disagreement where the reference
// (vobject 0.9.9) is the side that cannot represent the data, or where the
// reference deliberately shares no mapping knowledge with us (our v3 X-*
// extension convention).
//
// The near-absence of v4 ours->reference pins is itself the point: our
// vCard 4.0 exporter's output is read back semantically-equivalently by an
// independent implementation for everything vobject can represent.
func registerVCardPins() {
	if vcardPinsRegistered {
		return
	}
	vcardPinsRegistered = true
	checkPin(DivergencePin{CorpusID: "fixture/ada", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "impp", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "fixture/bob", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "impp", "photo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; vobject escapes/mangles the \";\"-containing inline data: PHOTO URI on re-serialization, and our importer does not unescape \"\\;\" in a URI value (documented reference divergence, issue #496)"})
	checkPin(DivergencePin{CorpusID: "fixture/celine", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "fixture/hugo", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "fixture/test07_country_code_only_address", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "fixture/test07_empty_note_with_params", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"note"}, Reason: "vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "fixture/test07_timestamped_birthday", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"anniversary.birth"}, Reason: "vobject parses BDAY as a DATE, dropping the time component of a timestamped birthday"})
	checkPin(DivergencePin{CorpusID: "golden/adr-expanded.v4.vcf", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "golden/note-author.v4.vcf", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"note"}, Reason: "vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "golden/socialprofile.v4.vcf", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"social"}, Reason: "v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0000", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "note", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0001", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"anniversary.birth", "note"}, Reason: "vobject parses BDAY as a DATE, dropping the time component of a timestamped birthday; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0002", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "impp", "note", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0003", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "anniversary.birth", "note"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject parses BDAY as a DATE, dropping the time component of a timestamped birthday; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0004", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "impp", "org", "org.unit", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; vobject drops an ORG whose name component is whitespace-only (pathological fixture value); vobject drops an ORG whose name component is whitespace-only, taking the unit with it; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0005", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0006", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "note"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0007", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"anniversary.birth", "impp", "note", "social"}, Reason: "vobject parses BDAY as a DATE, dropping the time component of a timestamped birthday; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0008", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "impp", "note"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0009", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "anniversary.birth", "impp", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject parses BDAY as a DATE, dropping the time component of a timestamped birthday; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0010", Format: "vcard3", Dir: "ours->reference", Concepts: []string{"adr", "note"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "fixture/ada", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "impp", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "fixture/bob", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "impp", "photo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; vobject escapes/mangles the \";\"-containing inline data: PHOTO URI on re-serialization, and our importer does not unescape \"\\;\" in a URI value (documented reference divergence, issue #496)"})
	checkPin(DivergencePin{CorpusID: "fixture/celine", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "fixture/hugo", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "fixture/test07_country_code_only_address", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "fixture/test07_empty_note_with_params", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"note"}, Reason: "vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "golden/adr-expanded.v4.vcf", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "golden/n-expanded.v4.vcf", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"name.credential"}, Reason: "when a card carries both credential and generation, vobject returns the combined suffix value as credential"})
	checkPin(DivergencePin{CorpusID: "golden/note-author.v4.vcf", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"note"}, Reason: "vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "golden/socialprofile.v4.vcf", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"social"}, Reason: "v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0000", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "note", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0001", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"name.credential", "note"}, Reason: "when a card carries both credential and generation, vobject returns the combined suffix value as credential; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0002", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "impp", "note", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0003", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "note"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0004", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "impp", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0005", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0006", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "note"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0007", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"impp", "note", "social"}, Reason: "v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0008", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "impp", "note"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0009", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "impp", "social"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; v3 leg: the oracle maps IMPP service to our grouped X-SERVICE-TYPE extension property, which vobject cannot independently know; v3 leg: the oracle maps SOCIALPROFILE to our grouped X-SOCIALPROFILE/X-SERVICE-TYPE/X-USERNAME extension convention, which vobject cannot independently know"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0010", Format: "vcard3", Dir: "reference->ours", Concepts: []string{"adr", "note"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "fixture/bob", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "golden/adr-expanded.v4.vcf", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr", "adr.geo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build"})
	checkPin(DivergencePin{CorpusID: "golden/n-expanded.v4.vcf", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"name.generation"}, Reason: "vobject's N has no slot for the neutral generation component (RFC 9554); it collapses into the suffix slot and reads back as credential"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0000", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0001", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"name.generation", "name.surname2"}, Reason: "vobject's N has no slot for the neutral generation component (RFC 9554); it collapses into the suffix slot and reads back as credential; vobject's N has no secondary-surname slot (RFC 9554 surname2); it collapses into the family slot"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0002", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr", "adr.geo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0003", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr", "adr.geo", "name.surname2"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build; vobject's N has no secondary-surname slot (RFC 9554 surname2); it collapses into the family slot"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0004", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr", "adr.geo", "org", "org.unit"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build; vobject drops an ORG whose name component is whitespace-only (pathological fixture value); vobject drops an ORG whose name component is whitespace-only, taking the unit with it"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0005", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr", "adr.geo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0006", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0007", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"name.generation", "name.surname2"}, Reason: "vobject's N has no slot for the neutral generation component (RFC 9554); it collapses into the suffix slot and reads back as credential; vobject's N has no secondary-surname slot (RFC 9554 surname2); it collapses into the family slot"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0008", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0009", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr", "adr.geo", "anniversary.place.birth", "anniversary.place.death"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build; BIRTHPLACE is a plain TEXT value; a neutral place with only components degrades to full text; DEATHPLACE is a plain TEXT value; a neutral place with only components degrades to full text"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0010", Format: "vcard4", Dir: "ours->reference", Concepts: []string{"adr", "adr.geo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build"})
	checkPin(DivergencePin{CorpusID: "fixture/bob", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr", "photo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject escapes/mangles the \";\"-containing inline data: PHOTO URI on re-serialization, and our importer does not unescape \"\\;\" in a URI value (documented reference divergence, issue #496)"})
	checkPin(DivergencePin{CorpusID: "fixture/celine", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"name.phonetic"}, Reason: "reference-fidelity scope: the Python reference does not emit the RFC 9554 phonetic N variant (ALTID+PHONETIC+SCRIPT), so phonetic data is absent from the reference-built card"})
	checkPin(DivergencePin{CorpusID: "fixture/test07_empty_note_with_params", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"note"}, Reason: "vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "golden/adr-expanded.v4.vcf", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr", "adr.geo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build"})
	checkPin(DivergencePin{CorpusID: "golden/n-expanded.v4.vcf", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"name.credential", "name.generation"}, Reason: "when a card carries both credential and generation, vobject returns the combined suffix value as credential; vobject's N has no slot for the neutral generation component (RFC 9554); it collapses into the suffix slot and reads back as credential"})
	checkPin(DivergencePin{CorpusID: "golden/phonetic-n.v4.vcf", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"name.phonetic"}, Reason: "reference-fidelity scope: the Python reference does not emit the RFC 9554 phonetic N variant (ALTID+PHONETIC+SCRIPT), so phonetic data is absent from the reference-built card"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0000", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0001", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"name.credential", "name.generation", "name.surname2", "note"}, Reason: "when a card carries both credential and generation, vobject returns the combined suffix value as credential; vobject's N has no slot for the neutral generation component (RFC 9554); it collapses into the suffix slot and reads back as credential; vobject's N has no secondary-surname slot (RFC 9554 surname2); it collapses into the family slot; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0002", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr", "adr.geo", "name.phonetic"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build; reference-fidelity scope: the Python reference does not emit the RFC 9554 phonetic N variant (ALTID+PHONETIC+SCRIPT), so phonetic data is absent from the reference-built card"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0003", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr", "adr.geo", "name.phonetic", "name.surname2"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build; reference-fidelity scope: the Python reference does not emit the RFC 9554 phonetic N variant (ALTID+PHONETIC+SCRIPT), so phonetic data is absent from the reference-built card; vobject's N has no secondary-surname slot (RFC 9554 surname2); it collapses into the family slot"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0004", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr", "adr.geo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0005", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr", "adr.geo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0006", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr", "hobby"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; a hobby with an empty value and an INDEX param is dropped by our importer (the reference emits the empty HOBBY;INDEX line our exporter also declines to produce)"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0007", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"name.generation", "name.phonetic", "name.surname2", "note"}, Reason: "vobject's N has no slot for the neutral generation component (RFC 9554); it collapses into the suffix slot and reads back as credential; reference-fidelity scope: the Python reference does not emit the RFC 9554 phonetic N variant (ALTID+PHONETIC+SCRIPT), so phonetic data is absent from the reference-built card; vobject's N has no secondary-surname slot (RFC 9554 surname2); it collapses into the family slot; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0008", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr", "anniversary.place.death", "note"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; DEATHPLACE is a plain TEXT value; a neutral place with only components degrades to full text; vobject splits unquoted parameter values containing \":\" (CREATED timestamps, AUTHOR URIs) and drops empty-valued NOTE lines, so NOTE params do not survive a vobject round trip"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0009", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr", "adr.geo", "anniversary.place.birth", "anniversary.place.death", "name.phonetic"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build; BIRTHPLACE is a plain TEXT value; a neutral place with only components degrades to full text; DEATHPLACE is a plain TEXT value; a neutral place with only components degrades to full text; reference-fidelity scope: the Python reference does not emit the RFC 9554 phonetic N variant (ALTID+PHONETIC+SCRIPT), so phonetic data is absent from the reference-built card"})
	checkPin(DivergencePin{CorpusID: "seed/gen-0010", Format: "vcard4", Dir: "reference->ours", Concepts: []string{"adr", "adr.geo"}, Reason: "vobject ADR is the classic 7-slot shape; the extended RFC 9554 components (room/apartment/floor/building/number/block/direction/landmark/subdistrict/district) collapse into the extended/street slots, so the neutral components differ; vobject does not pair the standalone GEO property back to an address; coordinates are dropped on parse and not re-emitted on build"})
}
