package flakeledger

import (
	"fmt"
	"strings"
	"time"
)

// Policy constants (docs/development/testing.md "Flake ledger"): a test with
// at least DefaultThreshold passed-on-retry events inside DefaultWindowDays
// gets an auto-opened flaky-test issue.
const (
	DefaultWindowDays = 14
	DefaultThreshold  = 3
	// MaxHitLinks bounds the run links named in an issue.
	MaxHitLinks = 10
)

// Ledger is the aggregate over the window.
type Ledger struct {
	Now        time.Time
	WindowDays int
	Runs       int // runs inside the window that contributed at least one observation
	Tests      int // distinct (suite, test) pairs observed
	Rows       []Stats
}

type key struct{ suite, test string }

// Build aggregates runs created within windowDays before now. Per (run,
// suite, test) there is exactly one outcome, so Runs counts runs, not
// attempts. Rows holds only tests whose first attempt failed at least once,
// most flaky first.
func Build(runs []RunData, now time.Time, windowDays int) Ledger {
	l := Ledger{Now: now, WindowDays: windowDays}
	cutoff := now.AddDate(0, 0, -windowDays)
	stats := map[key]*Stats{}
	for _, rd := range runs {
		t, err := time.Parse(time.RFC3339, rd.Run.CreatedAt)
		if err != nil || t.Before(cutoff) || t.After(now) {
			continue
		}
		if len(rd.Suites) > 0 {
			l.Runs++
		}
		for suite, obs := range rd.Suites {
			for test, o := range obs {
				k := key{suite, test}
				s := stats[k]
				if s == nil {
					s = &Stats{Suite: suite, Test: test}
					stats[k] = s
				}
				s.Runs++
				switch o {
				case PassedOnRetry:
					s.PassedOnRetry++
				case Failed:
					s.Failed++
				}
				if o != Passed {
					s.Hits = append(s.Hits, Hit{URL: rd.Run.URL, Time: rd.Run.CreatedAt, Outcome: o})
				}
			}
		}
	}
	l.Tests = len(stats)
	for _, s := range stats {
		if s.FailedFirstAttempt() > 0 {
			l.Rows = append(l.Rows, *s)
		}
	}
	sortStats(l.Rows)
	return l
}

// Candidate is a test that crossed the auto-issue threshold.
type Candidate struct {
	Suite         string   `json:"suite"`
	Test          string   `json:"test"`
	Title         string   `json:"title"`
	PassedOnRetry int      `json:"passed_on_retry"`
	Failed        int      `json:"failed"`
	Runs          int      `json:"runs"`
	RunLinks      []string `json:"run_links"`
}

// IssueTitle is the stable key the issue script dedupes on.
func IssueTitle(suite, test string) string {
	t := "Flaky test: " + suite + " " + test
	if len(t) > 200 {
		t = t[:200]
	}
	return t
}

// Candidates applies the policy: >= threshold passed-on-retry events. closed
// maps an issue title to when it was last closed; events at or before that
// moment are not counted, so closing an issue with a root-cause note is not
// immediately undone by the same events still inside the window.
func Candidates(l Ledger, threshold int, closed map[string]time.Time) []Candidate {
	var out []Candidate
	for _, s := range l.Rows {
		title := IssueTitle(s.Suite, s.Test)
		after, hasClosed := closed[title]
		c := Candidate{Suite: s.Suite, Test: s.Test, Title: title, Runs: s.Runs, RunLinks: []string{}}
		for _, h := range s.Hits {
			if hasClosed {
				if ht, err := time.Parse(time.RFC3339, h.Time); err != nil || !ht.After(after) {
					continue
				}
			}
			switch h.Outcome {
			case PassedOnRetry:
				c.PassedOnRetry++
			case Failed:
				c.Failed++
			}
			if len(c.RunLinks) < MaxHitLinks {
				c.RunLinks = append(c.RunLinks, h.URL)
			}
		}
		if c.PassedOnRetry >= threshold {
			out = append(out, c)
		}
	}
	return out
}

// MaxRenderedRows bounds the markdown table.
const MaxRenderedRows = 100

func esc(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.ReplaceAll(s, "\n", " ")
}

// Render writes the ledger as markdown. Deterministic for a given Ledger so
// the golden test pins the format.
func Render(l Ledger, threshold int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Flake ledger\n\n")
	fmt.Fprintf(&b, "Generated by `go run ./cmd/flakeledger` (issue #1488). Advisory only: this never fails a PR.\n\n")
	fmt.Fprintf(&b, "- Window: %d days ending %s\n", l.WindowDays, l.Now.UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "- Runs with flake artifacts: %d; distinct tests observed: %d\n", l.Runs, l.Tests)
	fmt.Fprintf(&b, "- Policy: a test with %d or more passed-on-retry events in the window gets a `flaky-test` issue.\n\n", threshold)
	if len(l.Rows) == 0 {
		b.WriteString("No test failed a first attempt in the window.\n")
		return b.String()
	}
	b.WriteString("| Suite | Test | Runs | Failed first attempt | Passed on retry | Failed | Flake rate |\n")
	b.WriteString("|---|---|---:|---:|---:|---:|---:|\n")
	for i, s := range l.Rows {
		if i == MaxRenderedRows {
			fmt.Fprintf(&b, "\n%d more row(s) omitted.\n", len(l.Rows)-MaxRenderedRows)
			break
		}
		fmt.Fprintf(&b, "| %s | %s | %d | %d | %d | %d | %.0f%% |\n",
			esc(s.Suite), esc(s.Test), s.Runs, s.FailedFirstAttempt(), s.PassedOnRetry, s.Failed, s.FlakeRate()*100)
	}
	return b.String()
}
