// Package apibaseline implements the breaking-change detector for the /api/v1
// REST contract (MAINT-02, issue #491).
//
// The package extracts a canonical "contract surface" from backend/openapi.yaml
// and compares it against a committed, frozen baseline snapshot
// (testdata/v1.json, generated by cmd/genapibaseline). The comparison is a
// SUPERSET check: the current spec must still contain everything the baseline
// records. Removing an endpoint, dropping a parameter, deleting a schema
// field, changing a field's type, narrowing an optional field to required,
// shrinking an enum, or removing a response schema all fail the drift test;
// adding a field, endpoint, parameter, response, or enum value passes without
// touching the baseline.
//
// The baseline is the spec's own guarantee of the additive/non-breaking
// distinction from the policy doc (docs/breaking-change-policy.md): what it
// records today is what additive change is free to build on, and removing any
// of it is a flagged break. Regenerating the baseline (go run
// ./cmd/genapibaseline) is therefore the deliberate act of declaring a breaking
// change, not a routine build step.
package apibaseline

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// SpecPath is the OpenAPI document the baseline derives from, backend-relative.
const SpecPath = "openapi.yaml"

// BaselineFile is the committed baseline snapshot, package-relative.
const BaselineFile = "testdata/v1.json"

// BaselineVersion identifies the baseline's on-disk format. Bump when the
// recorded surface changes shape, not when the spec does.
const BaselineVersion = 1

// Baseline is the frozen contract surface: every operation and every component
// schema the spec documents, in a canonical, sorted form. It is generated from
// openapi.yaml and compared against the live spec by the drift test.
type Baseline struct {
	Version    int                `json:"version"`
	Operations []OperationSurface `json:"operations"`
	Schemas    []SchemaSurface    `json:"schemas"`
}

// OperationSurface records one (method, path) pair: its parameters
// (query/path/header), the request-body schema it accepts, and each response's
// status and schema.
type OperationSurface struct {
	Method      string             `json:"method"`
	Path        string             `json:"path"`
	Parameters  []ParameterSurface `json:"parameters"`
	RequestBody string             `json:"request_body,omitempty"`
	Responses   []ResponseSurface  `json:"responses"`
}

// ParameterSurface records one parameter's name, location, and whether it is
// required. Narrowing a parameter (adding `required`) is a break.
type ParameterSurface struct {
	Name     string `json:"name"`
	In       string `json:"in"`
	Required bool   `json:"required"`
}

// ResponseSurface records one documented response: its status code and the
// schema (by $ref name, or by inline type signature) it returns.
type ResponseSurface struct {
	Status string `json:"status"`
	Schema string `json:"schema"`
}

// SchemaSurface records one component schema: its property names with their
// type signature, required-ness, and enum values.
type SchemaSurface struct {
	Name       string            `json:"name"`
	Properties []PropertySurface `json:"properties"`
	Enum       []any             `json:"enum,omitempty"`
}

// PropertySurface records one schema property: its name, a canonical type
// signature, whether it is required, and any enum values.
type PropertySurface struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Required bool   `json:"required"`
	Enum     []any  `json:"enum,omitempty"`
}

// operationMethods are the HTTP methods the REST contract documents. The
// spec's paths may also carry an Options method (the CORS preflight handler is
// not part of the JSON contract and is deliberately absent from openapi.yaml).
var operationMethods = []string{"GET", "POST", "PUT", "PATCH", "DELETE"}

// Load parses and validates the spec.
func Load(specPath string) (*openapi3.T, error) {
	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = false
	doc, err := loader.LoadFromFile(specPath)
	if err != nil {
		return nil, fmt.Errorf("loading %s: %w", specPath, err)
	}
	if err := doc.Validate(context.Background()); err != nil {
		return nil, fmt.Errorf("%s failed validation: %w", specPath, err)
	}
	return doc, nil
}

// Extract returns the canonical baseline for doc: every operation and every
// component schema, sorted deterministically.
func Extract(doc *openapi3.T) *Baseline {
	b := &Baseline{Version: BaselineVersion}

	for _, path := range sortedPathKeys(doc.Paths) {
		pi := doc.Paths.Value(path)
		for _, method := range operationMethods {
			op := operationForMethod(pi, method)
			if op == nil {
				continue
			}
			os := OperationSurface{
				Method: method,
				Path:   path,
			}
			// Parameters may be declared on the path item (shared by all
			// operations) or on the operation itself. Collect both, keyed by
			// name+in so a path-level override dedupes.
			seen := map[string]bool{}
			for _, pr := range pi.Parameters {
				if pr == nil || pr.Value == nil {
					continue
				}
				key := pr.Value.In + ":" + pr.Value.Name
				if seen[key] {
					continue
				}
				seen[key] = true
				os.Parameters = append(os.Parameters, ParameterSurface{
					Name:     pr.Value.Name,
					In:       pr.Value.In,
					Required: pr.Value.Required,
				})
			}
			for _, pr := range op.Parameters {
				if pr == nil || pr.Value == nil {
					continue
				}
				key := pr.Value.In + ":" + pr.Value.Name
				if seen[key] {
					continue
				}
				seen[key] = true
				os.Parameters = append(os.Parameters, ParameterSurface{
					Name:     pr.Value.Name,
					In:       pr.Value.In,
					Required: pr.Value.Required,
				})
			}
			sort.Slice(os.Parameters, func(i, j int) bool {
				if os.Parameters[i].In != os.Parameters[j].In {
					return os.Parameters[i].In < os.Parameters[j].In
				}
				return os.Parameters[i].Name < os.Parameters[j].Name
			})

			if op.RequestBody != nil && op.RequestBody.Value != nil {
				if s := jsonSchema(op.RequestBody.Value.Content); s != nil {
					os.RequestBody = schemaKey(s)
				}
			}

			for _, status := range sortedResponseKeys(op.Responses) {
				rs := ResponseSurface{Status: status}
				if respRef := op.Responses.Value(status); respRef != nil && respRef.Value != nil {
					if s := jsonSchema(respRef.Value.Content); s != nil {
						rs.Schema = schemaKey(s)
					}
				}
				os.Responses = append(os.Responses, rs)
			}
			sort.Slice(os.Responses, func(i, j int) bool {
				return os.Responses[i].Status < os.Responses[j].Status
			})

			b.Operations = append(b.Operations, os)
		}
	}

	for _, name := range sortedSchemaKeys(doc.Components.Schemas) {
		ref := doc.Components.Schemas[name]
		ss := SchemaSurface{Name: name}
		if ref != nil && ref.Value != nil {
			ss.Properties = schemaProperties(ref.Value)
			if len(ref.Value.Enum) > 0 {
				ss.Enum = append(ss.Enum, ref.Value.Enum...)
			}
		}
		b.Schemas = append(b.Schemas, ss)
	}

	return b
}

// jsonSchema returns the application/json schema of a content map, or nil.
func jsonSchema(content openapi3.Content) *openapi3.SchemaRef {
	if content == nil {
		return nil
	}
	mt := content.Get("application/json")
	if mt == nil {
		return nil
	}
	return mt.Schema
}

// schemaKey produces a stable key for a schema used as a request/response
// body: the $ref target name when it is a component reference (the common
// case — this is what ties an operation to a named schema), otherwise an
// inline type signature.
func schemaKey(sr *openapi3.SchemaRef) string {
	if sr == nil {
		return ""
	}
	if sr.Ref != "" {
		if name, ok := strings.CutPrefix(sr.Ref, "#/components/schemas/"); ok {
			return "ref:" + name
		}
		return "ref:" + sr.Ref
	}
	return typeSignature(sr.Value)
}

// typeSignature produces a canonical signature for an inline schema: the
// primitive type, `array<…>` for arrays, `object` for objects, composed for
// allOf/oneOf/anyOf. Used only where a schema has no $ref; refs dominate this
// spec's bodies.
func typeSignature(s *openapi3.Schema) string {
	if s == nil {
		return ""
	}
	var parts []string
	for _, m := range s.AllOf {
		parts = append(parts, typeSignature(m.Value))
	}
	for _, m := range s.OneOf {
		parts = append(parts, typeSignature(m.Value))
	}
	for _, m := range s.AnyOf {
		parts = append(parts, typeSignature(m.Value))
	}
	if len(parts) > 0 {
		sort.Strings(parts)
		return "composed[" + strings.Join(parts, ",") + "]"
	}
	if s.Type != nil {
		t := strings.Join(*s.Type, "|")
		if strings.Contains(t, "array") && s.Items != nil {
			return "array<" + typeSignature(s.Items.Value) + ">"
		}
		if t != "" {
			return t
		}
	}
	if len(s.Properties) > 0 {
		return "object"
	}
	if len(s.Enum) > 0 {
		return "enum"
	}
	return ""
}

// schemaProperties returns a schema's properties with per-property type
// signature, required-ness, and enums, following $ref composition (allOf/
// oneOf/anyOf yield the union of their members' properties; a property is
// required if any member requires it). Sorted by name.
func schemaProperties(s *openapi3.Schema) []PropertySurface {
	if s == nil {
		return nil
	}
	index := map[string]PropertySurface{}

	// add folds one composition member (or the top-level schema) into index:
	// its composed sub-members first (recursively), then its direct properties
	// with required-ness from its own Required list.
	var add func(part *openapi3.Schema)
	add = func(part *openapi3.Schema) {
		if part == nil {
			return
		}
		for _, ref := range part.AllOf {
			add(ref.Value)
		}
		for _, ref := range part.OneOf {
			add(ref.Value)
		}
		for _, ref := range part.AnyOf {
			add(ref.Value)
		}
		required := map[string]bool{}
		for _, r := range part.Required {
			required[r] = true
		}
		for name, pref := range part.Properties {
			ps := index[name]
			ps.Name = name
			if pref != nil {
				ps.Type = schemaKey(pref)
				if pref.Value != nil && len(pref.Value.Enum) > 0 {
					ps.Enum = append([]any(nil), pref.Value.Enum...)
				}
			}
			if required[name] {
				ps.Required = true
			}
			index[name] = ps
		}
	}

	add(s)

	var out []PropertySurface
	for _, ps := range index {
		out = append(out, ps)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func sortedPathKeys(paths *openapi3.Paths) []string {
	keys := make([]string, 0, paths.Len())
	for _, k := range paths.Keys() {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedSchemaKeys(schemas openapi3.Schemas) []string {
	keys := make([]string, 0, len(schemas))
	for k := range schemas {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedResponseKeys(responses *openapi3.Responses) []string {
	if responses == nil {
		return nil
	}
	keys := responses.Keys()
	sort.Strings(keys)
	return keys
}

func operationForMethod(pi *openapi3.PathItem, method string) *openapi3.Operation {
	switch method {
	case "GET":
		return pi.Get
	case "POST":
		return pi.Post
	case "PUT":
		return pi.Put
	case "PATCH":
		return pi.Patch
	case "DELETE":
		return pi.Delete
	}
	return nil
}

// Read loads the committed baseline from the repo root.
func Read(repoRoot string) (*Baseline, error) {
	path := filepath.Join(repoRoot, "backend", "internal", "apibaseline", BaselineFile)
	data, err := os.ReadFile(path) // #nosec G304 -- path is not request input: repoRoot comes from findRepoRoot (walking up from the process's own CWD) and BaselineFile is a fixed internal constant. Only loaders running inside the repository call this.
	if err != nil {
		return nil, fmt.Errorf("reading baseline %s: %w", path, err)
	}
	return Parse(data)
}

// Parse decodes a baseline from its canonical JSON form.
func Parse(data []byte) (*Baseline, error) {
	var b Baseline
	if err := json.Unmarshal(data, &b); err != nil {
		return nil, fmt.Errorf("parsing baseline: %w", err)
	}
	if b.Version != BaselineVersion {
		return nil, fmt.Errorf("baseline version %d does not match supported version %d — regenerate with `go run ./cmd/genapibaseline`", b.Version, BaselineVersion)
	}
	return &b, nil
}

// CheckSuperset reports whether current (a freshly extracted baseline of the
// live spec) still contains everything baseline records. Returns a list of
// human-readable breaking-change descriptions; empty means the spec only grew.
func CheckSuperset(baseline, current *Baseline) []string {
	var problems []string

	curOps := map[string]OperationSurface{}
	for _, o := range current.Operations {
		curOps[o.Method+" "+o.Path] = o
	}
	for _, want := range baseline.Operations {
		got, ok := curOps[want.Method+" "+want.Path]
		if !ok {
			problems = append(problems, fmt.Sprintf("operation %s %s was removed", want.Method, want.Path))
			continue
		}
		// Parameters: every baseline parameter must still exist, and a
		// parameter that was optional must not become required (narrowing
		// accepted input). A required parameter becoming optional is a
		// widening and fine.
		gotParams := map[string]bool{}
		gotRequired := map[string]bool{}
		for _, p := range got.Parameters {
			gotParams[p.In+":"+p.Name] = true
			if p.Required {
				gotRequired[p.In+":"+p.Name] = true
			}
		}
		for _, wantParam := range want.Parameters {
			key := wantParam.In + ":" + wantParam.Name
			if !gotParams[key] {
				problems = append(problems, fmt.Sprintf("parameter %s %s on %s %s was removed", wantParam.In, wantParam.Name, want.Method, want.Path))
				continue
			}
			if !wantParam.Required && gotRequired[key] {
				problems = append(problems, fmt.Sprintf("parameter %s %s on %s %s became required (narrowing)", wantParam.In, wantParam.Name, want.Method, want.Path))
			}
		}
		// Request body: the schema an operation accepts must not change.
		if want.RequestBody != "" && want.RequestBody != got.RequestBody {
			problems = append(problems, fmt.Sprintf("request body schema on %s %s changed from %s to %s", want.Method, want.Path, want.RequestBody, got.RequestBody))
		}
		// Responses: every documented status must still exist, with the same
		// schema.
		gotResp := map[string]ResponseSurface{}
		for _, r := range got.Responses {
			gotResp[r.Status] = r
		}
		for _, wantResp := range want.Responses {
			gotRespSurf, ok := gotResp[wantResp.Status]
			if !ok {
				problems = append(problems, fmt.Sprintf("response %s on %s %s was removed", wantResp.Status, want.Method, want.Path))
				continue
			}
			if wantResp.Schema != "" && wantResp.Schema != gotRespSurf.Schema {
				problems = append(problems, fmt.Sprintf("response %s schema on %s %s changed from %s to %s", wantResp.Status, want.Method, want.Path, wantResp.Schema, gotRespSurf.Schema))
			}
		}
	}

	curSchemas := map[string]SchemaSurface{}
	for _, s := range current.Schemas {
		curSchemas[s.Name] = s
	}
	for _, want := range baseline.Schemas {
		got, ok := curSchemas[want.Name]
		if !ok {
			problems = append(problems, fmt.Sprintf("schema %s was removed", want.Name))
			continue
		}
		gotProps := map[string]PropertySurface{}
		for _, p := range got.Properties {
			gotProps[p.Name] = p
		}
		for _, wantProp := range want.Properties {
			gotProp, ok := gotProps[wantProp.Name]
			if !ok {
				problems = append(problems, fmt.Sprintf("field %s.%s was removed", want.Name, wantProp.Name))
				continue
			}
			if wantProp.Type != "" && wantProp.Type != gotProp.Type {
				problems = append(problems, fmt.Sprintf("field %s.%s type changed from %s to %s", want.Name, wantProp.Name, wantProp.Type, gotProp.Type))
			}
			if !wantProp.Required && gotProp.Required {
				problems = append(problems, fmt.Sprintf("field %s.%s became required (narrowing)", want.Name, wantProp.Name))
			}
			if len(wantProp.Enum) > 0 {
				gotEnum := map[any]bool{}
				for _, v := range gotProp.Enum {
					gotEnum[v] = true
				}
				for _, v := range wantProp.Enum {
					if !gotEnum[v] {
						problems = append(problems, fmt.Sprintf("enum value %v on field %s.%s was removed", v, want.Name, wantProp.Name))
					}
				}
			}
		}
		// Schema-level enum values that existed must still exist.
		if len(want.Enum) > 0 {
			gotEnum := map[any]bool{}
			for _, v := range got.Enum {
				gotEnum[v] = true
			}
			for _, v := range want.Enum {
				if !gotEnum[v] {
					problems = append(problems, fmt.Sprintf("enum value %v on schema %s was removed", v, want.Name))
				}
			}
		}
	}

	return problems
}

// Marshal renders the baseline in the canonical JSON form used for the
// committed snapshot.
func (b *Baseline) Marshal() ([]byte, error) {
	data, err := json.MarshalIndent(b, "", "  ")
	if err != nil { // # pragma: no cover — MarshalIndent of this struct can never fail
		return nil, err
	}
	return append(data, '\n'), nil
}

// findRepoRoot walks up from dir until it finds the repository root (the
// directory containing backend/openapi.yaml), so callers work from backend/
// and from anywhere below the repo.
func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil { // # pragma: no cover — Getwd fails only when the cwd has been deleted, which no test can arrange for its own process
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "backend", SpecPath)); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("repo root not found above %s (looked for backend/%s)", dir, SpecPath)
		}
		dir = parent
	}
}
