package apibaseline

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ref builds a $ref SchemaRef for synthetic specs.
func ref(name string) *openapi3.SchemaRef {
	return &openapi3.SchemaRef{Ref: "#/components/schemas/" + name}
}

func sch(t *testing.T, s *openapi3.Schema) *openapi3.SchemaRef {
	t.Helper()
	return &openapi3.SchemaRef{Value: s}
}

func strType(v string) *openapi3.Types {
	return &openapi3.Types{v}
}

// TestSchemaPropertiesComposition pins that schemaProperties folds composed
// members (allOf/oneOf/anyOf) into a union of their properties, marks a
// property required when any member requires it, and sorts deterministically.
func TestSchemaPropertiesComposition(t *testing.T) {
	base := &openapi3.Schema{
		Type:     newTypes("object"),
		Required: []string{"id"},
		Properties: openapi3.Schemas{
			"id": sch(t, &openapi3.Schema{Type: strType("integer")}),
		},
	}
	ext := &openapi3.Schema{
		Type:     newTypes("object"),
		Required: []string{"name"},
		Properties: openapi3.Schemas{
			"name":  sch(t, &openapi3.Schema{Type: strType("string")}),
			"extra": ref("SomethingElse"),
		},
	}
	composed := &openapi3.Schema{
		AllOf: openapi3.SchemaRefs{sch(t, base), sch(t, ext)},
	}

	props := schemaProperties(composed)
	assert.Len(t, props, 3)

	byName := map[string]PropertySurface{}
	for _, p := range props {
		byName[p.Name] = p
	}
	assert.True(t, byName["id"].Required, "id is required by the base member")
	assert.True(t, byName["name"].Required, "name is required by the ext member")
	assert.False(t, byName["extra"].Required, "extra is not required by either member")
	assert.Equal(t, "ref:SomethingElse", byName["extra"].Type)
	assert.Equal(t, "integer", byName["id"].Type)
}

// TestSchemaPropertiesOneOfAnyOf pins the oneOf/anyOf fold path and that a
// property's enum is captured.
func TestSchemaPropertiesOneOfAnyOf(t *testing.T) {
	member := &openapi3.Schema{
		Type: newTypes("object"),
		Properties: openapi3.Schemas{
			"kind": sch(t, &openapi3.Schema{Type: strType("string"), Enum: []any{"a", "b"}}),
		},
	}
	anyOf := &openapi3.Schema{AnyOf: openapi3.SchemaRefs{sch(t, member)}}

	props := schemaProperties(anyOf)
	require.Len(t, props, 1)
	assert.Equal(t, "kind", props[0].Name)
	assert.Equal(t, []any{"a", "b"}, props[0].Enum)
}

// TestSchemaPropertiesNilIsEmpty pins the nil-schema guard.
func TestSchemaPropertiesNilIsEmpty(t *testing.T) {
	assert.Nil(t, schemaProperties(nil))
}

// TestTypeSignature pins the inline type-signature forms the drift test relies
// on for non-ref request/response bodies: primitives, arrays, objects, and
// composed forms.
func TestTypeSignature(t *testing.T) {
	cases := []struct {
		name string
		s    *openapi3.Schema
		want string
	}{
		{"nil", nil, ""},
		{"object with properties", &openapi3.Schema{Properties: openapi3.Schemas{"a": sch(t, &openapi3.Schema{Type: strType("string")})}}, "object"},
		{"array", &openapi3.Schema{Type: strType("array"), Items: sch(t, &openapi3.Schema{Type: strType("string")})}, "array<string>"},
		{"primitive", &openapi3.Schema{Type: strType("string")}, "string"},
		{"enum without type", &openapi3.Schema{Enum: []any{"a"}}, "enum"},
		{"anyOf", &openapi3.Schema{AnyOf: openapi3.SchemaRefs{sch(t, &openapi3.Schema{Type: strType("string")}), sch(t, &openapi3.Schema{Type: strType("null")})}}, "composed[null,string]"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, typeSignature(tc.s))
		})
	}
}

// TestSchemaKey pins ref-key vs inline-signature resolution for bodies.
func TestSchemaKey(t *testing.T) {
	assert.Equal(t, "ref:Contact", schemaKey(ref("Contact")))
	assert.Equal(t, "ref:https://example.com/ext.json", schemaKey(&openapi3.SchemaRef{Ref: "https://example.com/ext.json"}))
	assert.Equal(t, "", schemaKey(nil))
	assert.Equal(t, "string", schemaKey(sch(t, &openapi3.Schema{Type: strType("string")})))
}

// TestLoadRejectsBrokenSpec pins the two Load error paths: a missing file and
// a syntactically broken document.
func TestLoadRejectsBrokenSpec(t *testing.T) {
	t.Run("missing file", func(t *testing.T) {
		_, err := Load("/nonexistent/openapi.yaml")
		require.Error(t, err)
	})

	t.Run("invalid document", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "invalid.yaml")
		// Valid YAML but not a valid OpenAPI 3.0 document (no `openapi`/
		// `info`/`paths`) — LoadFromFile parses it, doc.Validate rejects it.
		require.NoError(t, os.WriteFile(path, []byte("some: [valid, yaml]\nbut: not-openapi\n"), 0o600))
		_, err := Load(path)
		require.Error(t, err)
	})
}

// TestParseRejectsWrongVersion pins that a baseline generated by a different
// format version is rejected with a regeneration hint, rather than silently
// compared.
func TestParseRejectsWrongVersion(t *testing.T) {
	_, err := Parse([]byte(`{"version": 99}`))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "regenerate")
}

// TestReadRejectsMissingBaseline pins the Read error path.
func TestReadRejectsMissingBaseline(t *testing.T) {
	_, err := Read("/nonexistent/repo-root")
	require.Error(t, err)
}

// TestCheckSupersetEnumNarrowingOnField pins the per-field enum shrink check
// (distinct from the schema-level enum check).
func TestCheckSupersetEnumNarrowingOnField(t *testing.T) {
	base := &Baseline{
		Version: BaselineVersion,
		Schemas: []SchemaSurface{{
			Name: "Thing",
			Properties: []PropertySurface{{
				Name: "kind", Type: "string", Enum: []any{"a", "b"},
			}},
		}},
	}
	cur := &Baseline{
		Version: BaselineVersion,
		Schemas: []SchemaSurface{{
			Name: "Thing",
			Properties: []PropertySurface{{
				Name: "kind", Type: "string", Enum: []any{"a"},
			}},
		}},
	}
	msgs := CheckSuperset(base, cur)
	assert.Contains(t, msgs, "enum value b on field Thing.kind was removed")
}

func newTypes(v string) *openapi3.Types {
	return &openapi3.Types{v}
}

func strPtr(v string) *string {
	return &v
}
