package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// Kind values stored on ReachOutSuggestion.Kind — the three change categories
// the T177 detection job recognizes in this first cut. Relationship-status
// and new-LifeEvent triggers are explicitly deferred (see the GitHub issue's
// "what a design pass would need to settle" section) and have no token here.
const (
	ReachOutKindOrganization = "organization"
	ReachOutKindTitle        = "title"
	ReachOutKindAddress      = "address"
)

// Status values stored on ReachOutSuggestion.Status.
const (
	ReachOutStatusPending   = "pending"
	ReachOutStatusDismissed = "dismissed"
)

// ReachOutSuggestion is one detected "meaningful change" to a contact —
// org, title, or address — surfaced as a dismissible dashboard suggestion
// (issue #177's event-driven counterpart to cadence.overdue). Generated by
// services.DetectReachOutSuggestions from an AuditEvent before/after diff,
// never by direct user input.
//
// ReminderID points at a companion one-off Reminder created alongside this
// row, which rides the existing email/ntfy/Gotify/push delivery pipeline
// (services/notification_service.go is Reminder-shaped, not a standalone
// notifier — see the plan's delivery-mechanism decision). Completing or
// skipping that reminder flips this row to dismissed too
// (controllers/reminder_controller.go's CompleteReminder).
//
// System-generated, edge-shaped row (CLAUDE.md backend trap 7): no soft
// delete, matching RelationshipEdge/ExternalActivity's precedent — "dismiss"
// is a status update, never a delete, and there is no natural-key unique
// constraint to protect. UUID-string PK generated in BeforeCreate, mirroring
// RelationshipEdge/ExternalActivity's own BeforeCreate.
type ReachOutSuggestion struct {
	ID        string    `gorm:"primarykey" json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	UserID uint `gorm:"not null;index" json:"-"`

	// ContactVCardUID is the contact this suggestion concerns, by
	// Contact.VCardUID — the same reference shape LifeEvent/Preference/
	// FieldValue use.
	ContactVCardUID string `gorm:"column:contact_vcard_uid;not null;index" json:"contact_vcard_uid" validate:"required,uuid4"`

	// Kind ∈ organization|title|address (the ReachOutKind* constants above).
	Kind string `gorm:"not null" json:"kind" validate:"required,oneof=organization title address"`

	// OldValue/NewValue are the human-readable before/after values that made
	// this a meaningful change (e.g. old job title -> new job title).
	OldValue string `gorm:"column:old_value;not null;default:''" json:"old_value"`
	NewValue string `gorm:"column:new_value;not null;default:''" json:"new_value"`

	// AuditEventID is the AuditEvent whose before/after diff produced this
	// suggestion — provenance for debugging, not a dedup key (the
	// ReachOutCursor watermark is what prevents reprocessing).
	AuditEventID uint `gorm:"column:audit_event_id;not null" json:"audit_event_id"`

	// ReminderID is the companion one-off Reminder's ID (see the type doc
	// comment). Nil only if reminder creation somehow failed after this row
	// was already created — the detection job always attempts both together.
	ReminderID *uint `gorm:"column:reminder_id;index" json:"reminder_id,omitempty"`

	// Status ∈ pending|dismissed (the ReachOutStatus* constants above).
	Status string `gorm:"not null;default:pending;index" json:"status" validate:"required,oneof=pending dismissed"`
}

// BeforeCreate generates a UUID for new suggestions, mirroring
// RelationshipEdge/ExternalActivity's own BeforeCreate.
func (r *ReachOutSuggestion) BeforeCreate(tx *gorm.DB) error {
	if r.ID == "" {
		r.ID = uuid.New().String()
	}
	return nil
}

// ReachOutSuggestionResponse is a pending suggestion enriched with the
// contact's numeric ID/display name/photo thumbnail — the same
// N+1-avoidance shape services.OverdueCadence uses for the cadence-overdue
// dashboard block.
type ReachOutSuggestionResponse struct {
	ReachOutSuggestion
	ContactID      uint   `json:"contact_id"`
	ContactName    string `json:"contact_name"`
	PhotoThumbnail string `json:"photo_thumbnail,omitempty"`
}

// ReachOutCursor is the per-user watermark ("last AuditEvent.ID already
// scanned for reach-out triggers") that lets services.DetectReachOutSuggestions
// resume exactly where it left off without rescanning history or
// double-firing a suggestion for the same change. One row per user;
// UserID is the primary key (no separate surrogate ID needed — this is a
// pure per-user counter, not a listable/referenceable entity).
type ReachOutCursor struct {
	UserID           uint      `gorm:"column:user_id;primarykey" json:"-"`
	LastAuditEventID uint      `gorm:"column:last_audit_event_id;not null;default:0" json:"-"`
	UpdatedAt        time.Time `json:"-"`
}
