package schemafixture

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"mycorrhizal/database"
)

// schemaObject is one row of sqlite_master: a schema object's type, name, and
// the SQL that created it.
type schemaObject struct {
	Type string
	Name string
	SQL  string
}

// GenerateDump builds the schema-only dump for the given migration version —
// the schema exactly as the release whose highest applied migration is
// version would present it — and returns it as SQL text ready to be applied
// to a fresh database.
//
// The dump is produced by applying migrations 000001..version from the
// CURRENT embedded chain to a scratch database. That is equivalent to checking
// out the release tag and dumping its schema: the migration chain is frozen
// and append-only, so migrations 000001..version are byte-identical to the
// tagged release's own files (verified at generation time for every committed
// dump — see the schemas README). The dump contains:
//
//   - every non-internal schema object (CREATE TABLE / CREATE VIRTUAL TABLE /
//     CREATE INDEX / CREATE TRIGGER) from sqlite_master, in dependency order;
//   - the schema_migrations row for the version, so a fixture built from the
//     dump presents the correct version and a clean (non-dirty) flag — a
//     fixture that omitted it would test a different situation than the one
//     that occurs in production (MIG-01 action 3).
//
// The output is deterministic (no timestamps), so regenerating a dump and
// diffing it against the committed file is a real check — the
// TestSchemaDumpsReproduceCurrentChain test does exactly that.
func GenerateDump(version uint, tag string) (string, error) {
	dbPath := filepath.Join(os.TempDir(), fmt.Sprintf("mycorrhizal-genschema-%d-%s.db", version, tag))
	_ = os.Remove(dbPath)

	if err := database.MigrateUpTo(dbPath, version); err != nil {
		return "", fmt.Errorf("genschema: building schema at version %d: %w", version, err)
	}
	defer os.Remove(dbPath)

	db, err := database.OpenMigratedFile(dbPath)
	if err != nil {
		return "", fmt.Errorf("genschema: opening schema database: %w", err) // # pragma: no cover — the file was just migrated successfully
	}
	sqlDB, err := db.DB()
	if err != nil {
		return "", fmt.Errorf("genschema: accessing sql.DB: %w", err) // # pragma: no cover — DB() fails only on a closed handle
	}
	// Fold the WAL sidecar into the main file so the scratch file is a
	// complete, consistent snapshot before any raw reads.
	if _, err := sqlDB.Exec("PRAGMA wal_checkpoint(TRUNCATE)"); err != nil {
		_ = sqlDB.Close()
		return "", fmt.Errorf("genschema: checkpointing schema database: %w", err) // # pragma: no cover — a just-opened WAL database accepts a checkpoint
	}

	var objs []schemaObject
	if err := db.Raw(`
		SELECT type, name, sql FROM sqlite_master
		WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
		ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'index' THEN 2 WHEN 'trigger' THEN 3 ELSE 4 END, rowid
	`).Scan(&objs).Error; err != nil {
		_ = sqlDB.Close()
		return "", fmt.Errorf("genschema: reading sqlite_master: %w", err) // # pragma: no cover — sqlite_master always answers
	}
	if err := sqlDB.Close(); err != nil {
		return "", fmt.Errorf("genschema: closing schema database: %w", err) // # pragma: no cover — Close on an open handle does not fail
	}

	objs = filterShadowTables(objs)

	var b strings.Builder
	fmt.Fprintf(&b, "-- Schema-only dump for release %s (migration version %d).\n", tag, version)
	fmt.Fprintf(&b, "-- Generated by `cd backend && go run ./cmd/genschema -tag %s -version %d`\n", tag, version)
	fmt.Fprintf(&b, "-- from the embedded migration chain (frozen and append-only, so migrations\n")
	fmt.Fprintf(&b, "-- 000001..%06d are byte-identical to the tagged release's own files).\n", version)
	fmt.Fprintf(&b, "-- FROZEN: a historical schema never changes retroactively -- see README.md.\n")
	fmt.Fprintf(&b, "-- Do not hand-edit; regenerate instead.\n\n")
	fmt.Fprintf(&b, "PRAGMA foreign_keys=OFF;\n\n")

	for _, o := range objs {
		b.WriteString(strings.TrimRight(o.SQL, " \t;") + ";\n\n")
	}

	fmt.Fprintf(&b, "INSERT INTO schema_migrations (version, dirty) VALUES (%d, 0);\n", version)
	return b.String(), nil
}

// filterShadowTables drops the auto-created shadow tables that SQLite stores
// for virtual tables (FTS5 here) from a sqlite_master dump. A shadow table
// must NOT be re-created explicitly: when the dump is applied, the virtual
// table's CREATE (CREATE VIRTUAL TABLE ... USING fts5) creates its own shadow
// tables, and an explicit duplicate CREATE fails with "table ... already
// exists". Shadow tables are identified as any TABLE named
// "<virtual-table-name>_<something>"; the virtual table names come from the
// same dump, so a legitimate user table can never be misclassified. Only
// type='table' rows are filtered — FTS triggers legitimately share the
// `<virtual-table>_<suffix>` naming (contacts_fts_ai, ...) and must survive.
func filterShadowTables(objs []schemaObject) []schemaObject {
	virtual := map[string]bool{}
	for _, o := range objs {
		if strings.HasPrefix(o.SQL, "CREATE VIRTUAL TABLE") {
			virtual[o.Name] = true
		}
	}
	filtered := objs[:0]
	for _, o := range objs {
		shadow := o.Type == "table" && isShadowOfVirtual(o.Name, virtual)
		if !shadow {
			filtered = append(filtered, o)
		}
	}
	return filtered
}

func isShadowOfVirtual(name string, virtual map[string]bool) bool {
	for v := range virtual {
		if v != name && strings.HasPrefix(name, v+"_") {
			return true
		}
	}
	return false
}

// SchemaDumpsDirRel is the repo-root-relative directory holding the committed
// per-release schema dumps, mirroring canonicalfixture.ManifestRelPath's role
// for the manifest. The dumps are committed (reviewable in a PR diff, frozen)
// rather than generated at test time.
const SchemaDumpsDirRel = "backend/database/testdata/schemas"
