// Package schemafixture is the loader for the versioned migration fixtures
// (MIG-01, issue #436) that back the supported-upgrade test matrix (issue
// #529).
//
// The migration chain is linear and append-only, so a release's schema is
// fully determined by its highest applied migration version. For every release
// at or above the v0.6.0 floor the repo commits a schema-only SQL dump under
// backend/database/testdata/schemas/ — one per release, not per migration —
// each carrying the schema_migrations row so it presents the right version and
// a clean (non-dirty) flag. The loader here creates a temp database from a
// chosen dump and populates it from the canonical TEST-02 manifest
// (backend/internal/canonicalfixture) restricted to the columns that existed
// at that version. The migration (MIG-02), automated-upgrade (DEPLOY-02) and
// backup (BACKUP-01) suites all consume this package rather than each
// constructing its own historical schema.
//
// The dumps are generated by backend/cmd/genschema from the current embedded
// migration chain (frozen and append-only, so migrations 000001..N are
// byte-identical to what the tagged release shipped) and are FROZEN: a
// historical schema never changes retroactively. See the directory's README.md
// for the full procedure.
package schemafixture

import (
	"mycorrhizal/database"
)

// Release identifies one supported release and the migration version that
// defined its schema.
type Release struct {
	Tag     string
	Version uint
}

// SupportedReleases is the upgrade test matrix's release set (issue #529):
// every release at or above the v0.6.0 floor, in release order. The v0.6.0
// floor is deliberate — it is the last release before the hardening series
// began, and everything at or above it has a committed schema dump here.
//
// When a new release ships, add it here AND commit its dump (run
// `go run ./cmd/genschema` from backend/, see the schemas README). The
// completeness test (TestEverySupportedReleaseHasADump) and the
// docker-publish.yml release gate both fail until the dump exists.
var SupportedReleases = []Release{
	{Tag: "v0.6.0", Version: 31},
	{Tag: "v0.6.1", Version: 36},
	{Tag: "v0.6.2", Version: 43},
	{Tag: "v0.6.3", Version: 44},
	{Tag: "v0.6.4", Version: 45},
	{Tag: "v0.6.5", Version: 46},
}

// DumpFile returns the committed schema-dump filename for a release, e.g.
// "v0.6.0.sql". The naming mirrors the issue's `v0.6.N.sql` convention.
func DumpFile(r Release) string {
	return r.Tag + ".sql"
}

// FloorVersion is the migration version below which a database must refuse to
// migrate rather than do so best-effort. It lives in the database package
// (where the refusal is enforced); this re-exports it so consumers of the
// fixture set and the refusal can share one source of truth.
const FloorVersion = database.SupportedUpgradeFloorVersion

// FloorTag is the release that defined the floor.
const FloorTag = database.SupportedUpgradeFloorTag
