package perfbench

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"sort"
)

// BaselineFile is the committed baseline's path, relative to this package.
const BaselineFile = "testdata/baseline.json"

// ReportFile is the generated human-facing report's path, relative to the
// repo root.
const ReportFile = "docs/development/perf-benchmarks.md"

//go:embed testdata/baseline.json
var embeddedBaseline []byte

// Baseline is the committed, diffable record of every core operation's query
// count and result-set size at each measured profile, plus the growth class
// each is allowed. Wall-clock time is deliberately absent — it is
// CI-hardware-variable and lives only in the generated report.
type Baseline struct {
	Note     string   `json:"note"`
	Profiles []string `json:"profiles"`
	// Operations is keyed by Operation.Name. Go marshals string-keyed maps in
	// sorted key order, so the file is stable across regenerations.
	Operations map[string]OpBaseline `json:"operations"`
}

// OpBaseline is one operation's committed numbers.
type OpBaseline struct {
	Category       string                   `json:"category"`
	ExpectedGrowth GrowthClass              `json:"expected_growth"`
	Profiles       map[string]ProfileMetric `json:"profiles"`
}

// ProfileMetric is the deterministic pair recorded per (operation, profile).
type ProfileMetric struct {
	Queries    int64 `json:"queries"`
	ResultSize int   `json:"result_size"`
	RowScale   int   `json:"row_scale"`
}

const baselineNote = "Generated by `go run ./cmd/perfbench` (PERF-02, issue #469). Query counts and " +
	"result-set sizes are the deterministic regression gate; wall-clock time is in " +
	ReportFile + " and is indicative only. Regenerate — never hand-edit — when an " +
	"operation's query shape changes deliberately."

// BuildBaseline folds per-profile Result sets into a Baseline. profileOrder
// fixes the Profiles slice order (smallest first); any profile present in
// resultsByProfile but not listed is appended in name order.
func BuildBaseline(resultsByProfile map[string][]Result, profileOrder []string) Baseline {
	b := Baseline{Note: baselineNote, Operations: map[string]OpBaseline{}}

	seen := map[string]bool{}
	for _, p := range profileOrder {
		if _, ok := resultsByProfile[p]; ok && !seen[p] {
			b.Profiles = append(b.Profiles, p)
			seen[p] = true
		}
	}
	extra := make([]string, 0)
	for p := range resultsByProfile {
		if !seen[p] {
			extra = append(extra, p)
		}
	}
	sort.Strings(extra)
	b.Profiles = append(b.Profiles, extra...)

	for _, profile := range b.Profiles {
		for _, r := range resultsByProfile[profile] {
			op, ok := b.Operations[r.Operation]
			if !ok {
				op = OpBaseline{
					Category:       r.Category,
					ExpectedGrowth: r.ExpectedGrowth,
					Profiles:       map[string]ProfileMetric{},
				}
			}
			op.Profiles[profile] = ProfileMetric{
				Queries:    r.Queries,
				ResultSize: r.ResultSize,
				RowScale:   r.RowScale,
			}
			b.Operations[r.Operation] = op
		}
	}
	return b
}

// Marshal renders the baseline as the committed file's bytes (indented,
// trailing newline).
func (b Baseline) Marshal() ([]byte, error) {
	data, err := json.MarshalIndent(b, "", "  ")
	if err != nil {
		return nil, err // # pragma: no cover — this struct always marshals
	}
	return append(data, '\n'), nil
}

// LoadBaseline parses a baseline file from disk.
func LoadBaseline(path string) (Baseline, error) {
	data, err := os.ReadFile(path) // #nosec G304 -- path is a build-tool argument, not request input
	if err != nil {
		return Baseline{}, err
	}
	return parseBaseline(data)
}

// EmbeddedBaseline returns the baseline compiled into the test binary.
func EmbeddedBaseline() (Baseline, error) { return parseBaseline(embeddedBaseline) }

func parseBaseline(data []byte) (Baseline, error) {
	var b Baseline
	if err := json.Unmarshal(data, &b); err != nil {
		return Baseline{}, fmt.Errorf("perfbench: parsing baseline: %w", err)
	}
	return b, nil
}
