package perfbench

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"sort"
)

// DataMovementBaselineFile is the committed PERF-03 baseline's path, relative
// to this package.
const DataMovementBaselineFile = "testdata/datamovement-baseline.json"

// DataMovementReportFile is the generated PERF-03 report's path, relative to
// the repo root.
const DataMovementReportFile = "docs/development/data-movement-benchmarks.md"

//go:embed testdata/datamovement-baseline.json
var embeddedDataMovementBaseline []byte

// DataMovementBaseline is the committed, diffable record of every bulk
// operation's DETERMINISTIC signals: how many rows it touches at each profile,
// the memory-growth class it is allowed, and whether it blocked concurrent
// writes for longer than the 5s busy_timeout. Wall-clock time, peak heap
// bytes and peak disk bytes are all environment-variable and live only in the
// generated report (DataMovementReportFile).
type DataMovementBaseline struct {
	Note     string   `json:"note"`
	Profiles []string `json:"profiles"`
	// Operations is keyed by DataMovementOperation.Name; Go marshals
	// string-keyed maps in sorted order, so the file is stable.
	Operations map[string]DataMovementOpBaseline `json:"operations"`
}

// DataMovementOpBaseline is one operation's committed numbers.
type DataMovementOpBaseline struct {
	Category             string                               `json:"category"`
	ExpectedMemoryGrowth GrowthClass                          `json:"expected_memory_growth"`
	Profiles             map[string]DataMovementProfileMetric `json:"profiles"`
}

// DataMovementProfileMetric is the deterministic tuple recorded per
// (operation, profile).
type DataMovementProfileMetric struct {
	RowsTouched   int  `json:"rows_touched"`
	RowScale      int  `json:"row_scale"`
	ProbeStalled  bool `json:"probe_stalled_out"`
	OutputPresent bool `json:"output_present"`
}

const dataMovementBaselineNote = "Generated by `go run ./cmd/perfbench` (PERF-03, issue #470). Rows-touched, the " +
	"memory-growth class and the >5s write-lock stall flag are the deterministic gate; " +
	"wall-clock time, peak heap and peak disk are in " + DataMovementReportFile + " and are " +
	"indicative only. Regenerate — never hand-edit — when an operation's shape changes deliberately."

// BuildDataMovementBaseline folds per-profile results into a baseline.
func BuildDataMovementBaseline(byProfile map[string][]DataMovementResult, profileOrder []string) DataMovementBaseline {
	b := DataMovementBaseline{Note: dataMovementBaselineNote, Operations: map[string]DataMovementOpBaseline{}}

	seen := map[string]bool{}
	for _, p := range profileOrder {
		if _, ok := byProfile[p]; ok && !seen[p] {
			b.Profiles = append(b.Profiles, p)
			seen[p] = true
		}
	}
	extra := make([]string, 0)
	for p := range byProfile {
		if !seen[p] {
			extra = append(extra, p)
		}
	}
	sort.Strings(extra)
	b.Profiles = append(b.Profiles, extra...)

	for _, profile := range b.Profiles {
		for _, r := range byProfile[profile] {
			op, ok := b.Operations[r.Operation]
			if !ok {
				op = DataMovementOpBaseline{
					Category:             r.Category,
					ExpectedMemoryGrowth: r.ExpectedMemoryGrowth,
					Profiles:             map[string]DataMovementProfileMetric{},
				}
			}
			op.Profiles[profile] = DataMovementProfileMetric{
				RowsTouched:   r.Sample.RowsTouched,
				RowScale:      r.RowScale,
				ProbeStalled:  r.Sample.ProbeStalledOut,
				OutputPresent: r.Sample.OutputBytes > 0,
			}
			b.Operations[r.Operation] = op
		}
	}
	return b
}

// Marshal renders the committed file's bytes (indented, trailing newline).
func (b DataMovementBaseline) Marshal() ([]byte, error) {
	data, err := json.MarshalIndent(b, "", "  ")
	if err != nil {
		return nil, err // # pragma: no cover — this struct always marshals
	}
	return append(data, '\n'), nil
}

// LoadDataMovementBaseline parses a baseline file from disk.
func LoadDataMovementBaseline(path string) (DataMovementBaseline, error) {
	data, err := os.ReadFile(path) // #nosec G304 -- build-tool argument, not request input
	if err != nil {
		return DataMovementBaseline{}, err
	}
	return parseDataMovementBaseline(data)
}

// EmbeddedDataMovementBaseline returns the baseline compiled into the binary.
func EmbeddedDataMovementBaseline() (DataMovementBaseline, error) {
	return parseDataMovementBaseline(embeddedDataMovementBaseline)
}

func parseDataMovementBaseline(data []byte) (DataMovementBaseline, error) {
	var b DataMovementBaseline
	if err := json.Unmarshal(data, &b); err != nil {
		return DataMovementBaseline{}, fmt.Errorf("perfbench: parsing data-movement baseline: %w", err)
	}
	return b, nil
}
