package perfbench

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"runtime"
	"sort"
)

// WallClockTrendFile is the committed rolling wall-clock record's path,
// relative to this package.
const WallClockTrendFile = "testdata/wallclock-trend.json"

//go:embed testdata/wallclock-trend.json
var embeddedWallClockTrend []byte

// wallClockTrendReviewRatio is the fold change (in either direction) at which
// a wall-clock move is surfaced for human review. Deliberately generous —
// this is a "someone should look", not a gate, and CI-runner noise alone can
// move a sub-millisecond operation by 2x.
const wallClockTrendReviewRatio = 3.0

const wallClockTrendNote = "Generated by `go run ./cmd/perfbench` (PERF-04, issue #471). A ROLLING record of " +
	"the wall-clock median (core) / duration (data-movement) per operation per profile. It is NOT a " +
	"gate and NOT drift-checked — `TestBenchmarksAtScale` / `TestDataMovementAtScale` compare a fresh " +
	"run against it and emit a `::warning::` for a >3x move in either direction (issue #471 action 3: " +
	"wall-clock is a trend for human review, never a build failure on a noisy runner). Cross-arch " +
	"comparisons are skipped. Regenerate freely with `make gen-perf-baseline`."

// WallClockTrend is the committed wall-clock history the at-scale tests
// compare a fresh run against.
type WallClockTrend struct {
	Note string `json:"note"`
	// GeneratedOn is GOOS/GOARCH. A trend comparison between two records made
	// on different architectures is meaningless and is skipped.
	GeneratedOn string `json:"generated_on"`
	// Core and DataMovement are operation -> profile -> nanoseconds (the core
	// median, the data-movement duration).
	Core         map[string]map[string]int64 `json:"core"`
	DataMovement map[string]map[string]int64 `json:"data_movement"`
}

// BuildWallClockTrend folds two measured suites into a trend record. Either
// suite may be empty (the gated tests build one side at a time).
func BuildWallClockTrend(core Suite, dm DataMovementSuite) WallClockTrend {
	t := WallClockTrend{
		Note:         wallClockTrendNote,
		GeneratedOn:  runtime.GOOS + "/" + runtime.GOARCH,
		Core:         map[string]map[string]int64{},
		DataMovement: map[string]map[string]int64{},
	}
	for profile, rs := range core.ResultsByProfile {
		for _, r := range rs {
			if t.Core[r.Operation] == nil {
				t.Core[r.Operation] = map[string]int64{}
			}
			t.Core[r.Operation][profile] = r.MedianNanos
		}
	}
	for profile, rs := range dm.ResultsByProfile {
		for _, r := range rs {
			if t.DataMovement[r.Operation] == nil {
				t.DataMovement[r.Operation] = map[string]int64{}
			}
			t.DataMovement[r.Operation][profile] = r.Sample.DurationNanos
		}
	}
	return t
}

// Marshal renders the committed file's bytes (indented, trailing newline).
func (t WallClockTrend) Marshal() ([]byte, error) {
	data, err := json.MarshalIndent(t, "", "  ")
	if err != nil {
		return nil, err // # pragma: no cover — this struct always marshals
	}
	return append(data, '\n'), nil
}

// EmbeddedWallClockTrend returns the trend record compiled into the binary.
func EmbeddedWallClockTrend() (WallClockTrend, error) {
	var t WallClockTrend
	if err := json.Unmarshal(embeddedWallClockTrend, &t); err != nil {
		return WallClockTrend{}, fmt.Errorf("perfbench: parsing wall-clock trend: %w", err) // # pragma: no cover — the committed file always parses
	}
	return t, nil
}

// TrendMove is one operation whose wall-clock moved past the review ratio
// since the committed trend.
type TrendMove struct {
	Scope     string  `json:"scope"` // "core" | "data_movement"
	Operation string  `json:"operation"`
	Profile   string  `json:"profile"`
	PrevNanos int64   `json:"prev_nanos"`
	CurrNanos int64   `json:"curr_nanos"`
	Ratio     float64 `json:"ratio"` // max(curr/prev, prev/curr), always >= 1
}

// CompareWallClock flags every (operation, profile) whose wall-clock moved by
// at least `threshold`x in either direction between prev and curr. The second
// return is false — with no moves — when the two records are not comparable
// (different or missing GOOS/GOARCH); a cross-hardware ratio is noise, not a
// signal (issue #261).
func CompareWallClock(prev, curr WallClockTrend, threshold float64) ([]TrendMove, bool) {
	if prev.GeneratedOn == "" || prev.GeneratedOn != curr.GeneratedOn {
		return nil, false
	}
	var moves []TrendMove
	scan := func(scope string, prevScope, currScope map[string]map[string]int64) {
		for op, byProfile := range currScope {
			for profile, cur := range byProfile {
				pv, ok := prevScope[op][profile]
				if !ok || pv <= 0 || cur <= 0 {
					continue
				}
				r := float64(cur) / float64(pv)
				if r < 1 {
					r = 1 / r
				}
				if r >= threshold {
					moves = append(moves, TrendMove{
						Scope: scope, Operation: op, Profile: profile,
						PrevNanos: pv, CurrNanos: cur, Ratio: round2(r),
					})
				}
			}
		}
	}
	scan("core", prev.Core, curr.Core)
	scan("data_movement", prev.DataMovement, curr.DataMovement)
	sort.Slice(moves, func(i, j int) bool {
		if moves[i].Scope != moves[j].Scope {
			return moves[i].Scope < moves[j].Scope
		}
		if moves[i].Operation != moves[j].Operation {
			return moves[i].Operation < moves[j].Operation
		}
		return moves[i].Profile < moves[j].Profile
	})
	return moves, true
}
