// Package largedata is the shared large-dataset generator (issue #495, the
// large-dataset migration test; PERF-01, issue #468, benchmark fixtures; and
// issue #498, capacity testing under constrained resources — one generator
// serves all three).
//
// It does NOT author a separate dataset. It takes the hand-authored canonical
// TEST-02 manifest (testdata/canonical-fixture/manifest.json, issue #430) and
// block-replicates it: each scaled "block" is a faithful copy of the whole
// manifest — every contact shape, every dependent row, every pathological
// record (the soft-deleted `gina`, the `julie` that re-uses her vcard_uid,
// the ~1700-char note, the Unicode and duplicate-duplicate pairs) — with
// contact names, card UIDs, and cross-references re-keyed so the block is
// internally consistent and the whole dataset validates.
//
// The result is "the same data shapes, more rows", by construction: whatever
// a migration or exporter does to the canonical dataset, it does to N blocks
// of it. Scaling to a target contact count is rounded UP to a whole number of
// blocks, so pathological records are always present at scale, never dropped
// by an off-by-one trim.
//
// The scaled manifest is populated exactly like the canonical one — through
// canonicalfixture.Populate, i.e. real migrated schemas and
// models.ApplyRecordToContact (CLAUDE.md backend traps #1 and #2), not a
// synthetic direct-INSERT path.
package largedata

import (
	"fmt"
	"strings"

	"github.com/google/uuid"

	"mycorrhizal/contactmodel"
	"mycorrhizal/internal/canonicalfixture"
)

// MinContacts is the smallest target ContactCount Scale accepts. Scale rounds
// up to a whole block (15 contacts each), so anything >= MinContacts yields
// at least one full manifest block.
const MinContacts = 1

// BlocksOfManifest is how many contact shapes the canonical manifest carries;
// it is the unit Scale replicates in. Kept as a constant so the round-up rule
// (and the tests asserting it) cannot drift from the manifest itself.
const BlocksOfManifest = 15

// Scale returns a copy of m block-replicated until it has at least
// targetContacts contacts. The copy is machine-generated: per-block comments
// are dropped (they explain why a hand-authored row exists) and names/UIDs are
// re-keyed, but every data field is preserved byte-for-byte, so the scaled
// dataset exercises the same paths — including the pathological ones — as the
// original manifest.
//
// The actual contact count is the smallest multiple of BlocksOfManifest that
// is >= targetContacts. The error paths exist so a caller that passes a nil
// manifest or a bad target fails loudly instead of scaling zero blocks.
func Scale(m *canonicalfixture.Manifest, targetContacts int) (*canonicalfixture.Manifest, error) {
	if m == nil {
		return nil, fmt.Errorf("largedata: nil manifest")
	}
	if targetContacts < MinContacts {
		return nil, fmt.Errorf("largedata: targetContacts must be >= %d, got %d", MinContacts, targetContacts)
	}
	if len(m.Contacts) == 0 {
		return nil, fmt.Errorf("largedata: manifest declares no contacts to scale")
	}

	return scaleSalted(m, targetContacts, "")
}

// scaleSalted is Scale with an explicit UID-derivation salt. An empty salt
// reproduces Scale's historical output byte-for-byte (the migration path and
// the scale-testing.md row-count table depend on that); a non-empty salt —
// used by the PERF-01 profile catalogue (profiles.go) to key each user's
// contacts distinctly — changes every regenerated card UID while leaving every
// data field untouched.
func scaleSalted(m *canonicalfixture.Manifest, targetContacts int, salt string) (*canonicalfixture.Manifest, error) {
	blocks := (targetContacts + len(m.Contacts) - 1) / len(m.Contacts)

	out := &canonicalfixture.Manifest{
		Version: m.Version,
		Description: fmt.Sprintf(
			"Machine-scaled copy of the canonical TEST-02 manifest (issue #430): %d manifest block(s) x %d contacts (%d total) for the large-dataset migration test (issue #495) / PERF-01 (issue #468). Generated by internal/largedata.Scale.",
			blocks, len(m.Contacts), blocks*len(m.Contacts)),
		User: m.User,
	}
	for b := 0; b < blocks; b++ {
		appendBlock(out, m, b, salt)
	}
	return out, nil
}

// rewriter re-keys one block of the scaled manifest: every contact name gets
// the block suffix, every card UID is regenerated deterministically, and
// every cross-reference (by name or by card UID) is rewritten to the block's
// re-keyed value.
type rewriter struct {
	block  int
	suffix string
	// uidOf maps a base contact name to this block's regenerated card UID.
	uidOf map[string]string
	// baseUID maps a base card UID back to its contact name, so card-level
	// references (relatedTo/members, which point at UIDs not names) can be
	// remapped.
	baseUID map[string]string
}

func newRewriter(m *canonicalfixture.Manifest, block int) *rewriter {
	return newRewriterSalted(m, block, "")
}

func newRewriterSalted(m *canonicalfixture.Manifest, block int, salt string) *rewriter {
	rw := &rewriter{
		block:   block,
		suffix:  fmt.Sprintf("_%06d", block),
		uidOf:   make(map[string]string, len(m.Contacts)),
		baseUID: make(map[string]string, len(m.Contacts)),
	}
	for i, c := range m.Contacts {
		uid := regeneratedUID(salt, block, i)
		rw.uidOf[c.Name] = uid
		if c.Card.UID != "" {
			rw.baseUID[c.Card.UID] = c.Name
		}
	}
	return rw
}

// regeneratedUID deterministically derives a new RFC 4122 v5 UUID for block b,
// contact index i (optionally namespaced by salt). Distinct per
// (salt, block, index), so the partial unique index idx_contacts_vcard_uid_user
// (WHERE deleted_at IS NULL) accepts every scaled contact under one user, and
// two users generated with different salts never collide. An empty salt keeps
// the historical derivation string so Scale's output is byte-stable.
func regeneratedUID(salt string, block, index int) string {
	key := fmt.Sprintf("largedata/block/%d/contact/%d", block, index)
	if salt != "" {
		key = fmt.Sprintf("largedata/%s/block/%d/contact/%d", salt, block, index)
	}
	return uuid.NewSHA1(uuid.Nil, []byte(key)).String()
}

// name re-keys a manifest contact name to this block.
func (rw *rewriter) name(name string) string {
	return name + rw.suffix
}

// remapUID returns the block's new UID for a base UID reference, and whether
// the reference pointed at a base contact at all.
func (rw *rewriter) remapUID(uid string) (string, bool) {
	name, ok := rw.baseUID[uid]
	if !ok {
		return "", false
	}
	return rw.uidOf[name], true
}

// uri rewrites a card-level reference that may be a bare UID or a
// "urn:uuid:<uid>" URI. Anything not pointing at a base contact passes
// through untouched.
func (rw *rewriter) uri(ref string) string {
	const prefix = "urn:uuid:"
	if strings.HasPrefix(ref, prefix) {
		if mapped, ok := rw.remapUID(strings.TrimPrefix(ref, prefix)); ok {
			return prefix + mapped
		}
		return ref
	}
	if mapped, ok := rw.remapUID(ref); ok {
		return mapped
	}
	return ref
}

// cloneStrings copies a []string so re-keying cannot mutate the base manifest's
// backing array (range-copying a struct copies the slice header, not the
// elements).
func cloneStrings(in []string) []string {
	if in == nil {
		return nil
	}
	out := make([]string, len(in))
	copy(out, in)
	return out
}

// appendBlock copies every section of m into out, re-keyed for block b (its
// regenerated card UIDs namespaced by salt — empty for Scale, per-user for the
// profile catalogue).
func appendBlock(out, m *canonicalfixture.Manifest, b int, salt string) {
	rw := newRewriterSalted(m, b, salt)

	for _, c := range m.Contacts {
		cp := c
		cp.Name = rw.name(c.Name)
		cp.Comment = "" // per-block trap comments would repeat 6,667 times; they explain the hand-authored row, not the copy
		if cp.RecreatesVCardUIDOf != "" {
			cp.RecreatesVCardUIDOf = rw.name(cp.RecreatesVCardUIDOf)
		}
		cp.Card.UID = rw.uidOf[c.Name]
		cp.Card.RelatedTo = append([]contactmodel.Relation(nil), cp.Card.RelatedTo...)
		for i := range cp.Card.RelatedTo {
			cp.Card.RelatedTo[i].Target = rw.uri(cp.Card.RelatedTo[i].Target)
		}
		cp.Card.Members = cloneStrings(cp.Card.Members)
		for i := range cp.Card.Members {
			cp.Card.Members[i] = rw.uri(cp.Card.Members[i])
		}
		out.Contacts = append(out.Contacts, cp)
	}

	for _, n := range m.Notes {
		n.Contact = rw.name(n.Contact)
		out.Notes = append(out.Notes, n)
	}
	for _, l := range m.LifeEvents {
		l.Contact = rw.name(l.Contact)
		l.RelatedEntities = cloneStrings(l.RelatedEntities)
		for i := range l.RelatedEntities {
			l.RelatedEntities[i] = rw.name(l.RelatedEntities[i])
		}
		out.LifeEvents = append(out.LifeEvents, l)
	}
	for _, g := range m.Gifts {
		g.Contact = rw.name(g.Contact)
		out.Gifts = append(out.Gifts, g)
	}
	for _, r := range m.Relationships {
		r.Source = rw.name(r.Source)
		r.Target = rw.name(r.Target)
		out.Relationships = append(out.Relationships, r)
	}
	for _, h := range m.Households {
		h.Name = rw.name(h.Name)
		h.Members = append([]canonicalfixture.HouseholdMemberEntry(nil), h.Members...)
		for i := range h.Members {
			h.Members[i].Contact = rw.name(h.Members[i].Contact)
		}
		out.Households = append(out.Households, h)
	}
	for _, c := range m.Circles {
		c.Name = rw.name(c.Name)
		c.Members = cloneStrings(c.Members)
		for i := range c.Members {
			c.Members[i] = rw.name(c.Members[i])
		}
		out.Circles = append(out.Circles, c)
	}
	for _, t := range m.Tags {
		t.Name = rw.name(t.Name)
		t.Contacts = cloneStrings(t.Contacts)
		for i := range t.Contacts {
			t.Contacts[i] = rw.name(t.Contacts[i])
		}
		out.Tags = append(out.Tags, t)
	}
	for _, f := range m.CustomFields {
		// idx_field_definitions_user_key is (user_id, key) unique, so the
		// definition key must be re-keyed per block; the human label is re-keyed
		// too so the two stay aligned.
		f.Key = rw.name(f.Key)
		f.Label = rw.name(f.Label)
		f.Values = append([]canonicalfixture.FieldValueEntry(nil), f.Values...)
		for i := range f.Values {
			f.Values[i].Contact = rw.name(f.Values[i].Contact)
		}
		out.CustomFields = append(out.CustomFields, f)
	}
	for _, p := range m.Preferences {
		p.Contact = rw.name(p.Contact)
		out.Preferences = append(out.Preferences, p)
	}
	for _, e := range m.ExternalIdentities {
		// idx_external_identities_system_ext_user is (system, external_id,
		// user_id) unique, so the external ID must be re-keyed per block.
		e.Contact = rw.name(e.Contact)
		e.ExternalID = rw.name(e.ExternalID)
		out.ExternalIdentities = append(out.ExternalIdentities, e)
	}
	for _, a := range m.Attachments {
		a.Contact = rw.name(a.Contact)
		out.Attachments = append(out.Attachments, a)
	}
	for _, a := range m.Activities {
		a.Contacts = cloneStrings(a.Contacts)
		for i := range a.Contacts {
			a.Contacts[i] = rw.name(a.Contacts[i])
		}
		out.Activities = append(out.Activities, a)
	}
}
